#!/usr/bin/env python3
"""Generate DPEN022 Limits+Differentiation and Integration lesson packs."""
from pathlib import Path
from _dpen22_lesson_kit import generate


def _set(slug, short, group, source, title, blurb, lesson, example, points, formulas, qa, **extra):
    problems, answers = zip(*qa)
    assert len(qa) == 15
    s = {
        'slug': slug, 'short': short, 'group': group, 'source': source,
        'title': title, 'blurb': blurb, 'lesson': lesson, 'example': example,
        'points': points, 'formulas': formulas,
        'problems': list(problems), 'answers': list(answers),
    }
    s.update(extra)
    return s


def _grp(label, sets):
    return {'label': label, 'sets': sets}


def validate(groups):
    for g in groups.values():
        for s in g['sets']:
            assert len(s['problems']) == 15, f"{s['slug']}: {len(s['problems'])} problems"
            assert len(s['answers']) == 15, f"{s['slug']}: {len(s['answers'])} answers"
            for i, t in enumerate(s['problems'] + s['answers'] + s['lesson'] + s['points'] + s['formulas'] + [s['blurb'], s.get('example','')], 1):
                assert '\t' not in t, f"{s['slug']}: literal tab in text {i}: {t!r}"


LD_GROUPS = {}

LD_GROUPS['2d'] = _grp('Week 2D — Limits', [
_set('w2d-set1', '2D Set 1', 'WEEK 2D · SET 1 OF 3', 'Student Notes Week 2D (filled-in)',
     'Introduction to limits & direct substitution',
     'From Week 2D: limit notation, reading graphs, and evaluating limits by substitution when the function is defined at the point.',
     [
         r'The <strong>limit</strong> \(\displaystyle\lim_{x\to a} f(x)\) describes the value \(f(x)\) approaches as \(x\) gets close to \(a\) (from either side). It may exist even when \(f(a)\) is undefined.',
         r'If \(f\) is continuous at \(a\), then \(\displaystyle\lim_{x\to a} f(x)=f(a)\). This is <strong>direct substitution</strong>: plug in \(x=a\) after checking the function is well-behaved there.',
         r'Use tables or graphs to estimate limits when an expression is awkward; exact work often starts with substitution, then algebra if you get an indeterminate form.',
     ],
     r'\(\displaystyle\lim_{x\to 3}(2x^2-5)=2(9)-5=13\).',
     [r'Limit notation uses \(x\to a\), not \(x=a\).', r'Continuous functions: substitute \(x=a\).', r'A limit can exist when \(f(a)\) does not.', 'Estimate from a graph or table when needed.', r'Indeterminate forms such as \(\frac00\) need other methods (next sets).'],
     [r'\(\displaystyle\lim_{x\to a} f(x)=L\) means \(f(x)\to L\) as \(x\to a\)', r'If \(f\) continuous at \(a\): \(\displaystyle\lim_{x\to a} f(x)=f(a)\)', r'\(\displaystyle\lim_{x\to c} k = k\) for constant \(k\)', r'\(\displaystyle\lim_{x\to 0}\frac{\sin x}{x}=1\)'],
     [
         (r'\(\displaystyle\lim_{x\to 2}(3x+1)\)', r'\(7\)'),
         (r'\(\displaystyle\lim_{x\to -1}(x^2-4)\)', r'\(-3\)'),
         (r'\(\displaystyle\lim_{x\to 0}(5x^2+3x+2)\)', r'\(2\)'),
         (r'\(\displaystyle\lim_{x\to 4}\sqrt{x}\)', r'\(2\)'),
         (r'\(\displaystyle\lim_{x\to 1}(x^3+2x)\)', r'\(3\)'),
         (r'\(\displaystyle\lim_{x\to \pi/6}\sin x\)', r'\(\dfrac12\)'),
         (r'\(\displaystyle\lim_{x\to 0}\cos x\)', r'\(1\)'),
         (r'\(\displaystyle\lim_{x\to 3}(2x-7)\)', r'\(-1\)'),
         (r'\(\displaystyle\lim_{x\to -2}(x^2+x+1)\)', r'\(3\)'),
         (r'\(\displaystyle\lim_{x\to 5}\dfrac{x+1}{x-1}\)', r'\(\dfrac32\)'),
         (r'\(\displaystyle\lim_{x\to 0}|x|\)', r'\(0\)'),
         (r'\(\displaystyle\lim_{x\to 1}(4-x^2)\)', r'\(3\)'),
         (r'\(\displaystyle\lim_{x\to \pi/4}\tan x\)', r'\(1\)'),
         (r'\(\displaystyle\lim_{x\to 2}(x^2-3x+4)\)', r'\(2\)'),
         (r'\(\displaystyle\lim_{x\to 0}\dfrac{\sin x}{x}\)', r'\(1\)'),
     ], formulas_title='Key limit results'),
_set('w2d-set2', '2D Set 2', 'WEEK 2D · SET 2 OF 3', 'Student Notes Week 2D (filled-in)',
     r'Limits by factorisation (\(0/0\) forms)',
     r'From Week 2D: when direct substitution gives \(\frac00\), factor numerator and denominator, cancel common factors, then substitute.',
     [
         r'If substituting \(x=a\) gives \(\dfrac00\), the limit may still exist. The fraction often has a common factor \((x-a)\) in top and bottom.',
         r'<strong>Factorise</strong> (difference of squares, common factors, quadratics), cancel matching factors, then substitute \(x=a\) into the simplified expression.',
         r'Always state the cancelled factor is non-zero near \(a\) (except at \(a\) itself), so the simplified function has the same limit.',
     ],
     r'\(\displaystyle\lim_{x\to 3}\frac{x^2-9}{x-3}=\lim_{x\to 3}\frac{(x-3)(x+3)}{x-3}=\lim_{x\to 3}(x+3)=6\).',
     [r'\(\frac00\) is indeterminate — do not stop there.', 'Factorise before cancelling.', r'Check domain: cancelled factor \(\neq 0\) near \(a\).', 'After cancelling, use direct substitution.', r'Difference of squares: \(a^2-b^2=(a-b)(a+b)\).'],
     [r'\(\dfrac{x^2-a^2}{x-a}=x+a\) for \(x\neq a\)', r'\(\dfrac{x^2-ax}{x-a}=x\) when \(a\neq 0\)', r'Cancel common factors, then \(\displaystyle\lim_{x\to a}=\) substitute', r'\(\displaystyle\lim_{x\to 0}\frac{1-\cos x}{x}=0\) (multiply by conjugate or use series)'],
     [
         (r'\(\displaystyle\lim_{x\to 3}\frac{x^2-9}{x-3}\)', r'\(6\)'),
         (r'\(\displaystyle\lim_{x\to 2}\frac{x^2-4}{x-2}\)', r'\(4\)'),
         (r'\(\displaystyle\lim_{x\to -1}\frac{x^2-1}{x+1}\)', r'\(-2\)'),
         (r'\(\displaystyle\lim_{x\to 0}\frac{x^2+x}{x}\)', r'\(1\)'),
         (r'\(\displaystyle\lim_{x\to 4}\frac{x^2-16}{x-4}\)', r'\(8\)'),
         (r'\(\displaystyle\lim_{x\to 1}\frac{x^2-3x+2}{x-1}\)', r'\(-1\)'),
         (r'\(\displaystyle\lim_{x\to -2}\frac{x^2+3x+2}{x+2}\)', r'\(-1\)'),
         (r'\(\displaystyle\lim_{x\to 5}\frac{x^2-25}{x-5}\)', r'\(10\)'),
         (r'\(\displaystyle\lim_{x\to 0}\frac{x^2-2x}{x}\)', r'\(-2\)'),
         (r'\(\displaystyle\lim_{x\to 3}\frac{x^2-5x+6}{x-3}\)', r'\(1\)'),
         (r'\(\displaystyle\lim_{x\to -3}\frac{x^2+5x+6}{x+3}\)', r'\(-1\)'),
         (r'\(\displaystyle\lim_{x\to 2}\frac{x^3-8}{x-2}\)', r'\(12\)'),
         (r'\(\displaystyle\lim_{x\to 1}\frac{x^3-1}{x-1}\)', r'\(3\)'),
         (r'\(\displaystyle\lim_{x\to 0}\frac{x^2}{\sin x}\)', r'\(0\)'),
         (r'\(\displaystyle\lim_{x\to 2}\frac{x^2-x-2}{x-2}\)', r'\(3\)'),
     ], formulas_title='Key limit results'),
_set('w2d-set3', '2D Set 3', 'WEEK 2D · SET 3 OF 3', 'Student Notes Week 2D (filled-in)',
     'Infinite limits & limits at infinity',
     r'From Week 2D: vertical asymptotes (\(\pm\infty\)) and end behaviour as \(x\to\pm\infty\).',
     [
         r'\(\displaystyle\lim_{x\to a^+} f(x)=+\infty\) means \(f(x)\) grows without bound as \(x\) approaches \(a\) from the right. Similar definitions for \(a^-\) and \(-\infty\).',
         r'For rational functions at infinity, divide numerator and denominator by the highest power of \(x\). Dominant terms decide the limit.',
         r'A vertical asymptote at \(x=a\) occurs when the limit from one side is \(\pm\infty\). Horizontal asymptotes describe \(\displaystyle\lim_{x\to\pm\infty} f(x)\).',
     ],
     r'\(\displaystyle\lim_{x\to\infty}\frac{3x^2+1}{2x^2-x}=\lim_{x\to\infty}\frac{3+1/x^2}{2-1/x}=\dfrac32\).',
     [r'Compare highest powers for limits at \(\infty\).', r'Divide top and bottom by \(x^n\) where \(n\) is the largest power.', r'\(+\infty\) and \(-\infty\) describe unbounded growth.', 'One-sided limits matter near vertical asymptotes.', r'Horizontal asymptote \(y=L\) if \(\displaystyle\lim_{x\to\infty}f(x)=L\).'],
     [r'If degree(top) \(<\) degree(bottom): \(\displaystyle\lim_{x\to\infty}=0\)', r'If degrees equal: limit \(=\) ratio of leading coefficients', r'If degree(top) \(>\) degree(bottom): limit \(=\pm\infty\)', r'\(\displaystyle\lim_{x\to a^+}\frac{1}{x-a}=+\infty\) (when \(a\) finite)'],
     [
         (r'\(\displaystyle\lim_{x\to\infty}\frac{3x^2+1}{x^2+2}\)', r'\(3\)'),
         (r'\(\displaystyle\lim_{x\to\infty}\frac{2x+5}{x^2-1}\)', r'\(0\)'),
         (r'\(\displaystyle\lim_{x\to\infty}\frac{x^3-1}{2x^2+x}\)', r'\(+\infty\)'),
         (r'\(\displaystyle\lim_{x\to\infty}\frac{5x-1}{3x+4}\)', r'\(\dfrac53\)'),
         (r'\(\displaystyle\lim_{x\to -\infty}\frac{4x^2}{x^2+1}\)', r'\(4\)'),
         (r'\(\displaystyle\lim_{x\to 2^+}\frac{1}{x-2}\)', r'\(+\infty\)'),
         (r'\(\displaystyle\lim_{x\to 2^-}\frac{1}{x-2}\)', r'\(-\infty\)'),
         (r'\(\displaystyle\lim_{x\to 0^+}\frac{1}{x^2}\)', r'\(+\infty\)'),
         (r'\(\displaystyle\lim_{x\to\infty}\frac{\sin x}{x}\)', r'\(0\)'),
         (r'\(\displaystyle\lim_{x\to\infty}\left(\sqrt{x^2+x}-x\right)\)', r'\(\dfrac12\)'),
         (r'\(\displaystyle\lim_{x\to\infty}\frac{1}{x}\)', r'\(0\)'),
         (r'\(\displaystyle\lim_{x\to -\infty}(x^3)\)', r'\(-\infty\)'),
         (r'\(\displaystyle\lim_{x\to\infty}\frac{6x^2-1}{3x^2+5}\)', r'\(2\)'),
         (r'\(\displaystyle\lim_{x\to 3^+}\frac{x+1}{x-3}\)', r'\(+\infty\)'),
         (r'\(\displaystyle\lim_{x\to\infty}\frac{x}{|x|}\)', r'\(1\)'),
     ], formulas_title='Key limit results'),
])

LD_GROUPS['3a'] = _grp('Week 3A — Power rule basics', [
_set('w3a-set1', '3A Set 1', 'WEEK 3A · SET 1 OF 3', 'Student Notes Week 3A (filled-in)',
     'Gradient function & meaning of the derivative',
     r"From Week 3A: average rate of change, gradient function \(f^{\prime}(x)\), and \(\dfrac{dy}{dx}\) notation.",
     [
         r'The <strong>derivative</strong> measures instantaneous rate of change. The gradient of \(y=f(x)\) at \(x=a\) is the slope of the tangent at that point.',
         r"The <strong>gradient function</strong> \(f^{\prime}(x)\) (or \(\dfrac{dy}{dx}\)) gives the slope at each \(x\). Notation: \(f^{\prime}(x)=\dfrac{d}{dx}f(x)\).",
         r'Average gradient on \([a,a+h]\) is \(\dfrac{f(a+h)-f(a)}{h}\). The derivative is the limit as \(h\to 0\) (first principles — rules come next).',
     ],
     r"For \(f(x)=x^2\), the gradient at \(x=3\) is \(f^{\prime}(3)=6\) (tangent slope \(6\)).",
     ['Derivative = instantaneous rate of change.', r"\(f^{\prime}(x)\) is the gradient function.", r"Notation: \(\dfrac{dy}{dx}\), \(f^{\prime}(x)\), \(\dfrac{d}{dx}f(x)\).", r"Tangent slope equals \(f^{\prime}(a)\) at \(x=a\).", 'Average gradient uses a chord slope.'],
     [r'Average gradient: \(\dfrac{f(a+h)-f(a)}{h}\)', r"\(f^{\prime}(a)=\displaystyle\lim_{h\to 0}\dfrac{f(a+h)-f(a)}{h}\)", r"Tangent at \(x=a\) has slope \(f^{\prime}(a)\)"],
     [
         (r"If \(f(x)=x^2\), find \(f^{\prime}(3)\).", r'\(6\)'),
         (r'If \(y=5x+2\), what is \(\dfrac{dy}{dx}\)?', r'\(5\)'),
         (r'State the gradient of \(y=3\) (constant).', r'\(0\)'),
         (r"If \(f^{\prime}(2)=-4\), describe the tangent at \(x=2\).", r'Decreasing; slope \(-4\).'),
         (r'Find average gradient of \(f(x)=x^2\) on \([1,3]\).', r'\(\dfrac{f(3)-f(1)}{2}=\dfrac{9-1}{2}=4\)'),
         (r"If \(f(x)=2x+1\), find \(f^{\prime}(x)\) by recognising linear slope.", r'\(2\)'),
         (r"What does \(f^{\prime}(a)>0\) tell you about \(f\) near \(a\)?", r'\(f\) is increasing at \(a\).'),
         (r"What does \(f^{\prime}(a)=0\) suggest at a turning point?", r'Horizontal tangent; possible max/min.'),
         (r'If \(y=x^2\), find \(\dfrac{dy}{dx}\big|_{x=-1}\).', r'\(-2\)'),
         (r'Write the gradient of the tangent to \(y=x^2\) at \(x=4\).', r'\(8\)'),
         (r"If \(f(x)=x^2+3x\), use \(f^{\prime}(x)=2x+3\) to find \(f^{\prime}(1)\).", r"\(5\)"),
         (r"Does \(f^{\prime}(a)\) depend on the value \(f(a)\)?", r'No — only on local rate of change.'),
         (r'If chord from \((2,4)\) to \((5,25)\) on \(y=x^2\), find chord slope.', r'\(7\)'),
         (r"Sketch idea: \(f^{\prime}(x)>0\) where \(y=x^2\) for \(x>0\).", r'Increasing for \(x>0\).'),
         (r"Units: if \(s(t)\) is metres, what are units of \(s^{\prime}(t)\)?", r'm/s (velocity).'),
     ]),
_set('w3a-set2', '3A Set 2', 'WEEK 3A · SET 2 OF 3', 'Student Notes Week 3A (filled-in)',
     'Power rule, constant multiple & sum rule',
     r'From Week 3A: differentiate polynomials using \(\dfrac{d}{dx}x^n=nx^{n-1}\), constant multiple and sum rules.',
     [
         r'The <strong>power rule</strong>: \(\dfrac{d}{dx}x^n=nx^{n-1}\) for real \(n\) (in this course, mainly integer \(n\)).',
         r"<strong>Constant multiple</strong>: \(\dfrac{d}{dx}[cf(x)]=c\,f^{\prime}(x)\). <strong>Sum rule</strong>: \(\dfrac{d}{dx}[f(x)+g(x)]=f^{\prime}(x)+g^{\prime}(x)\).",
         r'Differentiate term-by-term for polynomials. Constants differentiate to \(0\).',
     ],
     r'\(\dfrac{d}{dx}(3x^4-5x^2+7)=12x^3-10x\).',
     ['Power rule on each term.', r'Constants \(\to 0\).', 'Pull constants out (multiple rule).', 'Differentiate sums term by term.', 'Simplify before differentiating when helpful.'],
     [r'\(\dfrac{d}{dx}x^n=nx^{n-1}\)', r'\(\dfrac{d}{dx}c=0\)', r"\(\dfrac{d}{dx}[cf]=c\,f^{\prime}\)", r"\(\dfrac{d}{dx}[f+g]=f^{\prime}+g^{\prime}\)"],
     [
         (r'\(\dfrac{d}{dx}(x^5)\)', r'\(5x^4\)'),
         (r'\(\dfrac{d}{dx}(3x^2)\)', r'\(6x\)'),
         (r'\(\dfrac{d}{dx}(x^3-4x+1)\)', r'\(3x^2-4\)'),
         (r'\(\dfrac{d}{dx}(5)\)', r'\(0\)'),
         (r'\(\dfrac{d}{dx}(2x^4-x^2+7)\)', r'\(8x^3-2x\)'),
         (r'\(\dfrac{d}{dx}(-x^3+6x)\)', r'\(-3x^2+6\)'),
         (r"\(f(x)=4x^3\); find \(f^{\prime}(2)\).", r'\(48\)'),
         (r'\(\dfrac{d}{dx}(x^{-1})\) (write as power)', r'\(-x^{-2}=-\dfrac1{x^2}\)'),
         (r'\(\dfrac{d}{dx}(\sqrt{x})\)', r'\(\dfrac{1}{2\sqrt{x}}\)'),
         (r'\(\dfrac{d}{dx}(x^2+3x-5)\)', r'\(2x+3\)'),
         (r'\(\dfrac{d}{dx}(6x^5-3x)\)', r'\(30x^4-3\)'),
         (r'If \(y=2x^3\), find \(\dfrac{dy}{dx}\) at \(x=1\).', r'\(6\)'),
         (r'\(\dfrac{d}{dx}(x^4-2x^2)\)', r'\(4x^3-4x\)'),
         (r'\(\dfrac{d}{dx}(10-7x)\)', r'\(-7\)'),
         (r'\(\dfrac{d}{dx}(x^6)\)', r'\(6x^5\)'),
     ]),
_set('w3a-set3', '3A Set 3', 'WEEK 3A · SET 3 OF 3', 'Student Notes Week 3A (filled-in)',
     'Gradient at a point & simple applications',
     r"From Week 3A: evaluate \(f^{\prime}(a)\), interpret gradient, and use derivatives in basic motion problems.",
     [
         r"After finding \(f^{\prime}(x)\), substitute \(x=a\) to get the tangent slope at that point.",
         r"If \(s(t)\) is displacement, then \(v(t)=s^{\prime}(t)\) is velocity and \(a(t)=v^{\prime}(t)=s^{\prime\prime}(t)\) is acceleration.",
         r'Positive derivative \(\Rightarrow\) function increasing; negative \(\Rightarrow\) decreasing (locally).',
     ],
     r"For \(s(t)=t^2\), velocity at \(t=3\) is \(s^{\prime}(3)=6\) m/s.",
     [r"Evaluate \(f^{\prime}(a)\) after differentiating.", 'Velocity = derivative of displacement.', r"Sign of \(f^{\prime}\) shows increase/decrease.", r"Tangent slope \(=f^{\prime}(a)\).", 'Units follow from context.'],
     [r"\(v(t)=s^{\prime}(t)\)", r"\(a(t)=v^{\prime}(t)=s^{\prime\prime}(t)\)", r"Tangent slope at \(x=a\): \(m=f^{\prime}(a)\)"],
     [
         (r"\(f(x)=x^2+1\); find \(f^{\prime}(3)\).", r'\(6\)'),
         (r"\(f(x)=x^3-2x\); find \(f^{\prime}(-1)\).", r'\(1\)'),
         (r"\(s(t)=3t^2\); find \(s^{\prime}(2)\).", r'\(12\)'),
         (r"\(f(x)=2x^2-5x\); where is \(f^{\prime}(x)=0\)?", r'\(x=\dfrac54\)'),
         (r'\(f(x)=x^2\); is \(f\) increasing at \(x=2\)?', r"Yes (\(f^{\prime}(2)=4>0\))."),
         (r"\(f(x)=-x^2+4\); find \(f^{\prime}(1)\).", r'\(-2\)'),
         (r'\(y=5x^2\); gradient at \(x=-2\).', r'\(-20\)'),
         (r"\(f(x)=x^3\); find \(f^{\prime}(0)\).", r'\(0\)'),
         (r'\(s(t)=t^3-t\); velocity at \(t=1\).', r'\(2\)'),
         (r"\(f(x)=4x-x^2\); find \(f^{\prime}(2)\).", r'\(0\)'),
         (r"\(f(x)=x^2-6x+5\); find \(f^{\prime}(3)\).", r'\(0\)'),
         (r"\(f(x)=3x^2+2\); find \(f^{\prime}(-1)\).", r'\(-6\)'),
         (r"\(f(x)=x^4\); find \(f^{\prime}(2)\).", r'\(32\)'),
         (r"If \(f^{\prime}(x)=2x\) and \(f(1)=3\), is this consistent with \(f(x)=x^2+2\)?", r'Yes.'),
         (r"\(s(t)=-16t^2+64t\); find \(s^{\prime}(1)\).", r'\(32\)'),
     ]),
])

LD_GROUPS['3c'] = _grp('Week 3C — Quotient & chain rule', [
_set('w3c-set1', '3C Set 1', 'WEEK 3C · SET 1 OF 3', 'Student Notes Week 3C (filled-in)',
     'Quotient rule',
     r'From Week 3C: differentiate \(\dfrac{f(x)}{g(x)}\) using the quotient rule.',
     [
         r"The <strong>quotient rule</strong>: \(\dfrac{d}{dx}\!\left(\dfrac{u}{v}\right)=\dfrac{u^{\prime}v-uv^{\prime}}{v^2}\) (with \(v\neq 0\)).",
         r"Identify numerator \(u\) and denominator \(v\). Compute \(u^{\prime}\) and \(v^{\prime}\), then substitute into the formula.",
         r'For simple rational functions you may simplify first, but the quotient rule is the general method.',
     ],
     r'\(\dfrac{d}{dx}\!\left(\dfrac{x}{x+1}\right)=\dfrac{1\cdot(x+1)-x\cdot1}{(x+1)^2}=\dfrac{1}{(x+1)^2}\).',
     [r"Quotient: \(\dfrac{u^{\prime}v-uv^{\prime}}{v^2}\)", r"Label \(u\) (top) and \(v\) (bottom).", r"Square the denominator \(v^2\).", r"Simplify the numerator when possible.", r"Domain: \(v\neq 0\)."],
     [r"\(\dfrac{d}{dx}\!\left(\dfrac{u}{v}\right)=\dfrac{u^{\prime}v-uv^{\prime}}{v^2}\)", r"\(\dfrac{d}{dx}\!\left(\dfrac{1}{x}\right)=-\dfrac{1}{x^2}\)", r"\(\dfrac{d}{dx}\!\left(\dfrac{x}{a}\right)=\dfrac{1}{a}\) (constant \(a\))"],
     [
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{1}{x}\right)\)', r'\(-\dfrac{1}{x^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{x}{x+1}\right)\)', r'\(\dfrac{1}{(x+1)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{2x}{x^2+1}\right)\)', r'\(\dfrac{2-2x^2}{(x^2+1)^2}=\dfrac{2(1-x^2)}{(x^2+1)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{x^2}{x+2}\right)\)', r'\(\dfrac{x^2+4x}{(x+2)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{3}{x^2}\right)\)', r'\(-\dfrac{6}{x^3}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{x+1}{x-1}\right)\)', r'\(-\dfrac{2}{(x-1)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{5x}{2x+1}\right)\)', r'\(\dfrac{5}{(2x+1)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{x^2+1}{x}\right)\)', r'\(\dfrac{x^2-1}{x^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{1}{x+3}\right)\)', r'\(-\dfrac{1}{(x+3)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{4x}{x^2}\right)\)', r'\(-\dfrac{4}{x^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{x}{x^2+4}\right)\)', r'\(\dfrac{4-x^2}{(x^2+4)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{2}{3x-1}\right)\)', r'\(-\dfrac{6}{(3x-1)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{x^3}{x+1}\right)\)', r'\(\dfrac{2x^3+3x^2}{(x+1)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{1}{2x}\right)\)', r'\(-\dfrac{1}{2x^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{x^2+2x}{x+2}\right)\)', r'\(\dfrac{x^2+4x+4}{(x+2)^2}=\dfrac{(x+2)^2}{(x+2)^2}=1\) (for \(x\neq -2\))'),
     ]),
_set('w3c-set2', '3C Set 2', 'WEEK 3C · SET 2 OF 3', 'Student Notes Week 3C (filled-in)',
     'Chain rule',
     r'From Week 3C: differentiate composite functions \(f(g(x))\) using the chain rule.',
     [
         r'The <strong>chain rule</strong>: if \(y=f(u)\) and \(u=g(x)\), then \(\dfrac{dy}{dx}=\dfrac{dy}{du}\cdot\dfrac{du}{dx}\).',
         r"In Leibniz form: \(\dfrac{d}{dx}f(g(x))=f^{\prime}(g(x))\cdot g^{\prime}(x)\).",
         r'Identify the "outside" and "inside" functions. Differentiate the outside, keep the inside, multiply by derivative of inside.',
     ],
     r'\(\dfrac{d}{dx}(3x+1)^5=5(3x+1)^4\cdot 3=15(3x+1)^4\).',
     [r"Chain: \(f^{\prime}(g(x))\cdot g^{\prime}(x)\)", r"Identify inner \(g(x)\) and outer \(f\).", r"Differentiate outer, leave inner unchanged.", r"Multiply by derivative of inner.", r"Works for any composition."],
     [r"\(\dfrac{d}{dx}[f(g(x))]=f^{\prime}(g(x))\,g^{\prime}(x)\)", r"\(\dfrac{d}{dx}(ax+b)^n=n(ax+b)^{n-1}\cdot a\)", r"\(\dfrac{d}{dx}\sqrt{g(x)}=\dfrac{g^{\prime}(x)}{2\sqrt{g(x)}}\)"],
     [
         (r'\(\dfrac{d}{dx}(2x+1)^3\)', r'\(6(2x+1)^2\)'),
         (r'\(\dfrac{d}{dx}(x^2+1)^4\)', r'\(8x(x^2+1)^3\)'),
         (r'\(\dfrac{d}{dx}\sqrt{3x+1}\)', r'\(\dfrac{3}{2\sqrt{3x+1}}\)'),
         (r'\(\dfrac{d}{dx}(5-x)^2\)', r'\(-2(5-x)\)'),
         (r'\(\dfrac{d}{dx}(x^3-2x)^2\)', r'\(2(x^3-2x)(3x^2-2)\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{1}{2x+3}\right)\)', r'\(-\dfrac{2}{(2x+3)^2}\)'),
         (r'\(\dfrac{d}{dx}(4x^2+1)^5\)', r'\(40x(4x^2+1)^4\)'),
         (r'\(\dfrac{d}{dx}\sqrt{x^2+4}\)', r'\(\dfrac{x}{\sqrt{x^2+4}}\)'),
         (r'\(\dfrac{d}{dx}(x^2+3x)^{-1}\)', r'\(-(2x+3)(x^2+3x)^{-2}\)'),
         (r'\(\dfrac{d}{dx}(7-2x)^4\)', r'\(-8(7-2x)^3\)'),
         (r'\(\dfrac{d}{dx}(x^2-1)^{10}\)', r'\(20x(x^2-1)^9\)'),
         (r'\(\dfrac{d}{dx}\!\left(\dfrac{1}{\sqrt{x}}\right)\)', r'\(-\dfrac{1}{2x^{3/2}}\)'),
         (r'\(\dfrac{d}{dx}(3x^2+2x+1)^3\)', r'\(3(3x^2+2x+1)^2(6x+2)\)'),
         (r'\(\dfrac{d}{dx}(x^4+1)^{1/2}\)', r'\(\dfrac{2x^3}{\sqrt{x^4+1}}\)'),
         (r'\(\dfrac{d}{dx}(2x-5)^{-2}\)', r'\(-4(2x-5)^{-3}\)'),
     ]),
_set('w3c-set3', '3C Set 3', 'WEEK 3C · SET 3 OF 3', 'Student Notes Week 3C (filled-in)',
     'Combining differentiation rules',
     'From Week 3C: problems mixing product, quotient, and chain rules.',
     [
         r'Longer expressions need a plan: identify composition (chain), products, and quotients.',
         r'Often apply chain rule inside product or quotient terms. Differentiate step by step.',
         r'Simplify algebraically only after differentiating, unless simplification makes the derivative easier.',
     ],
     r'\(\dfrac{d}{dx}\!\left[x^2(2x+1)^3\right]=2x(2x+1)^3+x^2\cdot 3(2x+1)^2\cdot 2\) (product + chain).',
     ['Break into inside/outside for chain.', 'Product/quotient on factors.', 'Differentiate once per rule application.', 'Factor common terms at the end.', 'Check with a quick estimate if unsure.'],
     [r"Chain inside product: \((uv)^{\prime}=u^{\prime}v+uv^{\prime}\)", r"Quotient + chain on \(u/v\)", r"Simplify factors like \((2x+1)^2\) when factoring"],
     [
         (r'\(\dfrac{d}{dx}\!\left[x(3x-1)^2\right]\)', r'\((3x-1)^2+6x(3x-1)\)'),
         (r'\(\dfrac{d}{dx}\!\left[\dfrac{x^2}{x+1}\right]\)', r'\(\dfrac{x^2+2x}{(x+1)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left[x\sqrt{x+1}\right]\)', r'\(\sqrt{x+1}+\dfrac{x}{2\sqrt{x+1}}\)'),
         (r'\(\dfrac{d}{dx}\!\left[(x^2+1)(x-2)\right]\)', r'\(2x(x-2)+(x^2+1)\)'),
         (r'\(\dfrac{d}{dx}\!\left[\dfrac{2x+1}{x^2}\right]\)', r'\(\dfrac{-2x^2+2x(2x+1)}{x^4}=\dfrac{-2x^2+4x^2+2x}{x^4}=\dfrac{2x^2+2x}{x^4}\)'),
         (r'\(\dfrac{d}{dx}\!\left[(x+1)^3(2-x)\right]\)', r'\(3(x+1)^2(2-x)-(x+1)^3\)'),
         (r'\(\dfrac{d}{dx}\!\left[\dfrac{\sqrt{x}}{x+1}\right]\)', r'\(\dfrac{(x+1)\cdot\frac{1}{2\sqrt{x}}-\sqrt{x}}{(x+1)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left[x^2 e^{2x}\right]\)', r'\(2x e^{2x}+2x^2 e^{2x}\)'),
         (r'\(\dfrac{d}{dx}\!\left[\dfrac{x}{(2x+1)^2}\right]\)', r'\(\dfrac{(2x+1)^2-2x\cdot 2(2x+1)\cdot 2}{(2x+1)^4}\)'),
         (r'\(\dfrac{d}{dx}\!\left[(3x-2)^4\right]\)', r'\(12(3x-2)^3\)'),
         (r'\(\dfrac{d}{dx}\!\left[x\sin(2x)\right]\)', r'\(\sin(2x)+2x\cos(2x)\)'),
         (r'\(\dfrac{d}{dx}\!\left[\dfrac{1}{(x^2+1)^2}\right]\)', r'\(-\dfrac{4x}{(x^2+1)^3}\)'),
         (r'\(\dfrac{d}{dx}\!\left[(x^2-4)^{1/2}\right]\)', r'\(\dfrac{x}{\sqrt{x^2-4}}\)'),
         (r'\(\dfrac{d}{dx}\!\left[\dfrac{x^2+1}{x^2-1}\right]\)', r'\(\dfrac{-4x}{(x^2-1)^2}\)'),
         (r'\(\dfrac{d}{dx}\!\left[x^2(3x+1)^{-1}\right]\)', r'\(2x(3x+1)^{-1}-3x^2(3x+1)^{-2}\)'),
     ]),
])

LD_GROUPS['3b'] = _grp('Week 3B — Product rule & higher derivatives', [
_set('w3b-set1', '3B Set 1', 'WEEK 3B · SET 1 OF 3', 'Student Notes Week 3B (filled-in)',
     r"Finding \(f\) and \(f^{\prime}\) from information",
     'From Week 3B: given derivative or gradient conditions, recover parts of a function or evaluate at a point.',
     [
         r"Sometimes you know \(f^{\prime}(x)\) and one value \(f(a)\). Integrate the derivative (antiderivative idea) or match a template polynomial.",
         r"For polynomials, if \(f^{\prime}(x)\) is known, \(f(x)\) is an antiderivative plus constant: \(f(x)=\int f^{\prime}(x)\,dx + C\), then use \(f(a)\) to find \(C\).",
         r"Gradient at a point links to tangent problems: slope \(m=f^{\prime}(a)\) and point \((a,f(a))\).",
     ],
     r"If \(f^{\prime}(x)=2x\) and \(f(1)=5\), then \(f(x)=x^2+C\), \(1+C=5\Rightarrow C=4\), so \(f(x)=x^2+4\).",
     [r"Antiderivative + constant from \(f^{\prime}\).", r'Use a given point to find \(C\).', r"Polynomial \(f^{\prime}\) \(\Rightarrow\) polynomial \(f\).", 'Check by differentiating back.', r"Tangent slope is \(f^{\prime}(a)\)."],
     [r"If \(f^{\prime}(x)=g(x)\), then \(f(x)=\int g(x)\,dx + C\)", r'\(f(a)\) fixes \(C\)', r"Tangent slope at \(a\): \(f^{\prime}(a)\)"],
     [
         (r"\(f^{\prime}(x)=3x^2\), \(f(0)=2\). Find \(f(x)\).", r'\(f(x)=x^3+2\)'),
         (r"\(f^{\prime}(x)=4x\), \(f(2)=10\). Find \(f(1)\).", r'\(f(x)=2x^2+2\); \(f(1)=4\)'),
         (r"\(f^{\prime}(x)=1\), \(f(3)=7\). Find \(f(x)\).", r'\(f(x)=x+4\)'),
         (r"\(f^{\prime}(x)=2x-1\), \(f(1)=0\). Find \(f(2)\).", r'\(f(x)=x^2-x\); \(f(2)=2\)'),
         (r"\(f^{\prime}(x)=5\), \(f(0)=-1\). Find \(f(4)\).", r'\(19\)'),
         (r"\(f^{\prime}(x)=x^2\), \(f(1)=2\). Find \(f(-1)\).", r'\(f(x)=\dfrac{x^3}{3}+\dfrac53\); \(f(-1)=\dfrac43\)'),
         (r"\(f^{\prime}(x)=6x\), \(f(0)=1\). Find \(f(3)\).", r'\(28\)'),
         (r"\(f^{\prime}(x)=-2x\), \(f(2)=1\). Find \(f(0)\).", r'\(f(x)=-x^2+5\); \(f(0)=5\)'),
         (r"\(f^{\prime}(x)=3\), \(f(1)=4\). Find \(f(-2)\).", r'\(-5\)'),
         (r"\(f^{\prime}(x)=4x^3\), \(f(0)=0\). Find \(f(2)\).", r'\(16\)'),
         (r"\(f^{\prime}(x)=2x+3\), \(f(0)=1\). Find \(f(1)\).", r'\(5\)'),
         (r"\(f^{\prime}(x)=x\), \(f(2)=5\). Find \(f(0)\).", r'\(f(x)=\dfrac{x^2}{2}+3\); \(3\)'),
         (r"\(f^{\prime}(x)=7\), \(f(5)=20\). Find \(f(0)\).", r'\(-15\)'),
         (r"\(f^{\prime}(x)=5x^4\), \(f(1)=3\). Find \(f(-1)\).", r'\(f(x)=x^5+2\); \(1\)'),
         (r"\(f^{\prime}(x)=-4\), \(f(2)=0\). Find \(f(6)\).", r'\(-16\)'),
     ]),
_set('w3b-set2', '3B Set 2', 'WEEK 3B · SET 2 OF 3', 'Student Notes Week 3B (filled-in)',
     'Product rule',
     r'From Week 3B: differentiate products \(f(x)g(x)\) using \((fg)^{\prime}=f^{\prime}g+fg^{\prime}\).',
     [
         r"The <strong>product rule</strong>: if \(y=uv\) then \(\dfrac{dy}{dx}=u\dfrac{dv}{dx}+v\dfrac{du}{dx}\), or \((fg)^{\prime}=f^{\prime}g+fg^{\prime}\).",
         r'Identify factors clearly. Differentiate each factor, then add the two product terms.',
         r'Do not differentiate factor-by-factor separately — the product rule has two terms.',
     ],
     r'\(\dfrac{d}{dx}[x^2\sin x]=2x\sin x+x^2\cos x\).',
     [r"\((fg)^{\prime}=f^{\prime}g+fg^{\prime}\)", r"Label \(u\) and \(v\) (or \(f\) and \(g\)).", r"Differentiate each factor once.", r"Expand only if needed.", r"Check degree/terms make sense."],
     [r"\((fg)^{\prime}=f^{\prime}g+fg^{\prime}\)", r"\(\dfrac{d}{dx}[u\cdot v]=u v^{\prime}+v u^{\prime}\)", r"Constants factor through product rule"],
     [
         (r'\(\dfrac{d}{dx}[x(x+1)]\)', r'\(2x+1\)'),
         (r'\(\dfrac{d}{dx}[x^2\cdot x^3]\)', r'\(5x^4\)'),
         (r'\(\dfrac{d}{dx}[(2x+1)(x-3)]\)', r'\(4x-5\)'),
         (r'\(\dfrac{d}{dx}[x\sin x]\)', r'\(\sin x+x\cos x\)'),
         (r'\(\dfrac{d}{dx}[(x^2+1)(x)]\)', r'\(3x^2+1\)'),
         (r'\(\dfrac{d}{dx}[(x+2)^2]\) via product \((x+2)(x+2)\)', r'\(2x+4\)'),
         (r'\(\dfrac{d}{dx}[x^2 e^x]\)', r'\(2x e^x+x^2 e^x\)'),
         (r'\(\dfrac{d}{dx}[(3x)(x^2)]\)', r'\(9x^2\)'),
         (r'\(\dfrac{d}{dx}[(x-1)(x+1)]\)', r'\(2x\)'),
         (r'\(\dfrac{d}{dx}[x\cos x]\)', r'\(\cos x-x\sin x\)'),
         (r'\(\dfrac{d}{dx}[(x^2)(x+5)]\)', r'\(3x^2+10x\)'),
         (r'\(\dfrac{d}{dx}[(2x)(3x+1)]\)', r'\(12x+2\)'),
         (r'\(\dfrac{d}{dx}[x\cdot\sqrt{x}]\)', r'\(\dfrac{3}{2}\sqrt{x}\)'),
         (r'\(\dfrac{d}{dx}[(x^3+1)(2x)]\)', r'\(8x^3+2\)'),
         (r'\(\dfrac{d}{dx}[(x+4)(x^2)]\)', r'\(3x^2+8x\)'),
     ]),
_set('w3b-set3', '3B Set 3', 'WEEK 3B · SET 3 OF 3', 'Student Notes Week 3B (filled-in)',
     'Second derivatives',
     r"From Week 3B: notation \(f^{\prime\prime}(x)=\dfrac{d^2y}{dx^2}\), concavity, and acceleration as second derivative of displacement.",
     [
         r"The <strong>second derivative</strong> is the derivative of the first: \(f^{\prime\prime}(x)=\dfrac{d}{dx}f^{\prime}(x)=\dfrac{d^2y}{dx^2}\).",
         r"If \(s(t)\) is displacement, \(s^{\prime\prime}(t)=a(t)\) is acceleration.",
         r"Sign of \(f^{\prime\prime}\): \(f^{\prime\prime}>0\) concave up; \(f^{\prime\prime}<0\) concave down (locally).",
     ],
     r"For \(y=x^4\), \(y^{\prime}=4x^3\), \(y^{\prime\prime}=12x^2\).",
     [r"\(f^{\prime\prime}=(f^{\prime})^{\prime}\).", r"Acceleration \(=s^{\prime\prime}(t)\).", r"\(f^{\prime\prime}>0\): concave up.", r"\(f^{\prime\prime}<0\): concave down.", r"Differentiate twice for second derivative."],
     [r"\(f^{\prime\prime}(x)=\dfrac{d^2y}{dx^2}\)", r"\(a(t)=s^{\prime\prime}(t)\)", r"\(y^{\prime\prime}=\dfrac{d}{dx}(y^{\prime})\)"],
     [
         (r"\(f(x)=x^3\); find \(f^{\prime\prime}(x)\).", r"\(6x\)"),
         (r"\(f(x)=x^4\); find \(f^{\prime\prime}(2)\).", r"\(48\)"),
         (r"\(y=x^2\); find \(y^{\prime\prime}\).", r"\(2\)"),
         (r"\(s(t)=t^3-2t\); find \(s^{\prime\prime}(1)\).", r"\(6\)"),
         (r"\(f(x)=5x^2+3x\); find \(f^{\prime\prime}(x)\).", r"\(10\)"),
         (r"\(f(x)=x^5\); find \(f^{\prime\prime}(x)\).", r"\(20x^3\)"),
         (r"\(y=3x^3-6x\); find \(y^{\prime\prime}(0)\).", r"\(0\)"),
         (r"\(f(x)=2x^4-x^2\); find \(f^{\prime\prime}(1)\).", r"\(22\)"),
         (r"\(s(t)=-16t^2+32t\); find \(s^{\prime\prime}(t)\).", r"\(-32\)"),
         (r"\(f(x)=x^2+1\); find \(f^{\prime\prime}(x)\).", r"\(2\)"),
         (r"\(y=x^6\); find \(y^{\prime\prime}(x)\).", r"\(30x^4\)"),
         (r"\(f(x)=4x^3\); find \(f^{\prime\prime}(-1)\).", r"\(-24\)"),
         (r"\(f(x)=x^4-4x^2\); find \(f^{\prime\prime}(2)\).", r"\(40\)"),
         (r"\(s(t)=t^2\); acceleration at \(t=3\).", r"\(2\)"),
         (r"\(f(x)=x^3+x\); find \(f^{\prime\prime}(1)\).", r"\(6\)"),
     ]),
])

LD_GROUPS['3d'] = _grp('Week 3D — Tangents & exponentials', [
_set('w3d-set1', '3D Set 1', 'WEEK 3D · SET 1 OF 3', 'Student Notes Week 3D (filled-in)',
     'Equation of the tangent (point–gradient form)',
     r"From Week 3D: use \(y-y_1=m(x-x_1)\) with \(m=f^{\prime}(a)\) at the point of tangency.",
     [
         r"The tangent line at \((a,f(a))\) has slope \(m=f^{\prime}(a)\). Use <strong>point–gradient form</strong>: \(y-y_1=m(x-x_1)\).",
         r"Steps: (1) find \(f(a)\), (2) find \(f^{\prime}(a)\), (3) substitute into \(y-y_1=m(x-x_1)\), (4) simplify if required.",
         r'The tangent touches the curve at exactly one point (locally) and has the same slope as the curve there.',
     ],
     r"For \(f(x)=x^2\) at \(x=2\): point \((2,4)\), \(m=f^{\prime}(2)=4\), tangent \(y-4=4(x-2)\Rightarrow y=4x-4\).",
     [r"Slope \(m=f^{\prime}(a)\).", r'Point \((a,f(a))\).', r'Form: \(y-y_1=m(x-x_1)\).', r'Simplify to \(y=mx+c\) if asked.', 'Normal perpendicular to tangent (extra).'],
     [r'\(y-y_1=m(x-x_1)\)', r"\(m=f^{\prime}(a)\)", r'Point: \((a,f(a))\)'],
     [
         (r'\(f(x)=x^2\); tangent at \(x=1\).', r'\(y-1=2(x-1)\) or \(y=2x-1\)'),
         (r'\(f(x)=x^3\); tangent at \(x=2\).', r'\(y-8=12(x-2)\) or \(y=12x-16\)'),
         (r'\(f(x)=2x+3\); tangent at \(x=0\).', r'\(y=2x+3\) (line is its own tangent)'),
         (r'\(f(x)=x^2-4x\); tangent at \(x=3\).', r'\(f(3)=-3\), \(m=2\); \(y+3=2(x-3)\)'),
         (r'\(f(x)=x^2+1\); tangent at \(x=-1\).', r'\(y-2=-2(x+1)\)'),
         (r'\(f(x)=3x^2\); tangent at \(x=1\).', r'\(y-3=6(x-1)\)'),
         (r'\(f(x)=x^2+x\); find \(m\) at \(x=2\).', r"\(m=f^{\prime}(2)=5\)"),
         (r'\(f(x)=x^2\); tangent at origin?', r'\(y=0\) (horizontal tangent at \((0,0)\))'),
         (r'\(f(x)=-x^2+9\); tangent at \(x=2\).', r'\(y-5=-4(x-2)\)'),
         (r'\(f(x)=x^3-x\); tangent at \(x=1\).', r'\(y=2(x-1)\)'),
         (r'\(f(x)=4x^2\); tangent at \(x=-1\).', r'\(y-4=-8(x+1)\)'),
         (r'\(f(x)=x^2+2x\); tangent at \(x=0\).', r'\(y=2x\)'),
         (r'\(f(x)=5\); tangent at any point.', r'\(y=5\)'),
         (r'\(f(x)=x^2-1\); tangent at \(x=2\).', r'\(y-3=4(x-2)\)'),
         (r'\(f(x)=x^3\); tangent at \(x=-1\).', r'\(y+1=3(x+1)\)'),
     ]),
_set('w3d-set2', '3D Set 2', 'WEEK 3D · SET 2 OF 3', 'Student Notes Week 3D (filled-in)',
     r'Derivative of \(e^x\)',
     r'From Week 3D: the exponential function differentiates to itself: \(\dfrac{d}{dx}e^x=e^x\).',
     [
         r'The derivative of \(e^x\) is \(e^x\). This is the defining property of the natural exponential.',
         r'For \(y=ke^{ax}\), \(\dfrac{dy}{dx}=ka e^{ax}\) (chain rule with constant multiple).',
         r'The graph of \(e^x\) is always increasing; slope at any point equals the \(y\)-value there.',
     ],
     r'\(\dfrac{d}{dx}(3e^{2x})=6e^{2x}\).',
     [r'\(\dfrac{d}{dx}e^x=e^x\)', r'\(\dfrac{d}{dx}e^{ax}=a e^{ax}\)', 'Exponential growth: derivative equals height.', r'Chain rule for inner linear \(ax+b\).', r'\(e^0=1\).'],
     [r'\(\dfrac{d}{dx}e^x=e^x\)', r'\(\dfrac{d}{dx}e^{ax}=a e^{ax}\)', r'\(\dfrac{d}{dx}e^{ax+b}=a e^{ax+b}\)'],
     [
         (r'\(\dfrac{d}{dx}(e^x)\)', r'\(e^x\)'),
         (r'\(\dfrac{d}{dx}(e^{3x})\)', r'\(3e^{3x}\)'),
         (r'\(\dfrac{d}{dx}(2e^x)\)', r'\(2e^x\)'),
         (r'\(\dfrac{d}{dx}(e^{-x})\)', r'\(-e^{-x}\)'),
         (r'\(\dfrac{d}{dx}(5e^{2x})\)', r'\(10e^{2x}\)'),
         (r'\(\dfrac{d}{dx}(e^{x+1})\)', r'\(e^{x+1}\)'),
         (r'\(\dfrac{d}{dx}(-e^x)\)', r'\(-e^x\)'),
         (r"\(f(x)=e^{4x}\); find \(f^{\prime}(0)\).", r'\(4\)'),
         (r'\(\dfrac{d}{dx}(e^{x/2})\)', r'\(\dfrac{1}{2}e^{x/2}\)'),
         (r'\(\dfrac{d}{dx}(3e^{-2x})\)', r'\(-6e^{-2x}\)'),
         (r'\(\dfrac{d}{dx}(e^x+e^{-x})\)', r'\(e^x-e^{-x}\)'),
         (r'\(y=e^{5x}\); find \(\dfrac{dy}{dx}\) at \(x=0\).', r'\(5\)'),
         (r'\(\dfrac{d}{dx}(e^{2x+3})\)', r'\(2e^{2x+3}\)'),
         (r'\(\dfrac{d}{dx}(x e^x)\) (product)', r'\(e^x+x e^x\)'),
         (r'\(\dfrac{d}{dx}(e^{3x}-e^x)\)', r'\(3e^{3x}-e^x\)'),
     ]),
_set('w3d-set3', '3D Set 3', 'WEEK 3D · SET 3 OF 3', 'Student Notes Week 3D (filled-in)',
     r'Derivative of \(e^{f(x)}\)',
     r"From Week 3D: chain rule for exponentials — \(\dfrac{d}{dx}e^{f(x)}=f^{\prime}(x)e^{f(x)}\).",
     [
         r"For any differentiable \(f(x)\), \(\dfrac{d}{dx}e^{f(x)}=f^{\prime}(x)\,e^{f(x)}\).",
         r'Identify the exponent as \(f(x)\), differentiate it, multiply by \(e^{f(x)}\).',
         r'Combines chain rule with \(\dfrac{d}{dx}e^u=e^u\dfrac{du}{dx}\).',
     ],
     r'\(\dfrac{d}{dx}e^{x^2}=2x e^{x^2}\).',
     [r"\(\dfrac{d}{dx}e^{f(x)}=f^{\prime}(x)e^{f(x)}\)", 'Differentiate the exponent.', 'Multiply by original exponential.', 'Works for any inner function.', 'Common in growth/decay models.'],
     [r"\(\dfrac{d}{dx}e^{f(x)}=f^{\prime}(x)e^{f(x)}\)", r'\(\dfrac{d}{dx}e^{x^2}=2x e^{x^2}\)', r'\(\dfrac{d}{dx}e^{\sin x}=\cos x\, e^{\sin x}\)'],
     [
         (r'\(\dfrac{d}{dx}e^{x^2}\)', r'\(2x e^{x^2}\)'),
         (r'\(\dfrac{d}{dx}e^{3x+1}\)', r'\(3e^{3x+1}\)'),
         (r'\(\dfrac{d}{dx}e^{\sin x}\)', r'\(\cos x\, e^{\sin x}\)'),
         (r'\(\dfrac{d}{dx}e^{x^3}\)', r'\(3x^2 e^{x^3}\)'),
         (r'\(\dfrac{d}{dx}e^{\sqrt{x}}\)', r'\(\dfrac{e^{\sqrt{x}}}{2\sqrt{x}}\)'),
         (r'\(\dfrac{d}{dx}e^{-x^2}\)', r'\(-2x e^{-x^2}\)'),
         (r'\(\dfrac{d}{dx}e^{2x^2+1}\)', r'\(4x e^{2x^2+1}\)'),
         (r'\(\dfrac{d}{dx}e^{\cos x}\)', r'\(-\sin x\, e^{\cos x}\)'),
         (r'\(\dfrac{d}{dx}e^{5x}\)', r'\(5e^{5x}\)'),
         (r'\(\dfrac{d}{dx}e^{x^2+2x}\)', r'\((2x+2)e^{x^2+2x}\)'),
         (r'\(\dfrac{d}{dx}e^{1/x}\)', r'\(-\dfrac{e^{1/x}}{x^2}\)'),
         (r'\(\dfrac{d}{dx}e^{\ln x}\)', r'\(\dfrac{1}{x}\) (since \(e^{\ln x}=x\))'),
         (r'\(\dfrac{d}{dx}e^{x^2}\) at \(x=1\).', r'\(2e\)'),
         (r'\(\dfrac{d}{dx}(x^2 e^{x^2})\)', r'\(2x e^{x^2}+2x^3 e^{x^2}\)'),
         (r'\(\dfrac{d}{dx}e^{2\sin x}\)', r'\(2\cos x\, e^{2\sin x}\)'),
     ]),
])

LD_GROUPS['4a'] = _grp('Week 4A — Log & trig derivatives', [
_set('w4a-set1', '4A Set 1', 'WEEK 4A · SET 1 OF 3', 'Student Notes Week 4A (filled-in)',
     r'Derivatives of \(\ln x\) and \(\ln(f(x))\)',
     r"From Week 4A: \(\dfrac{d}{dx}\ln x=\dfrac1x\) and chain rule gives \(\dfrac{d}{dx}\ln(f(x))=\dfrac{f^{\prime}(x)}{f(x)}\).",
     [
         r'\(\dfrac{d}{dx}\ln x=\dfrac{1}{x}\) for \(x>0\).',
         r"By the chain rule, \(\dfrac{d}{dx}\ln(f(x))=\dfrac{f^{\prime}(x)}{f(x)}\) (logarithmic differentiation idea).",
         r'Domain: argument of \(\ln\) must be positive.',
     ],
     r'\(\dfrac{d}{dx}\ln(3x^2+1)=\dfrac{6x}{3x^2+1}\).',
     [r'\(\dfrac{d}{dx}\ln x=\dfrac1x\)', r"\(\dfrac{d}{dx}\ln(f)=\dfrac{f^{\prime}}{f}\)", r'Argument of log must be \(>0\).', 'Simplify logs using laws when helpful.', 'Chain rule on the inside.'],
     [r'\(\dfrac{d}{dx}\ln x=\dfrac{1}{x}\)', r'\(\dfrac{d}{dx}\ln(ax)=\dfrac{1}{x}\)', r"\(\dfrac{d}{dx}\ln(f(x))=\dfrac{f^{\prime}(x)}{f(x)}\)"],
     [
         (r'\(\dfrac{d}{dx}(\ln x)\)', r'\(\dfrac{1}{x}\)'),
         (r'\(\dfrac{d}{dx}(\ln(2x))\)', r'\(\dfrac{1}{x}\)'),
         (r'\(\dfrac{d}{dx}(\ln(x^2+1))\)', r'\(\dfrac{2x}{x^2+1}\)'),
         (r'\(\dfrac{d}{dx}(\ln(3x))\)', r'\(\dfrac{1}{x}\)'),
         (r'\(\dfrac{d}{dx}(\ln(x^2))\)', r'\(\dfrac{2}{x}\)'),
         (r'\(\dfrac{d}{dx}(\ln(5-x))\)', r'\(\dfrac{-1}{5-x}\)'),
         (r'\(\dfrac{d}{dx}(\ln(x^3+2x))\)', r'\(\dfrac{3x^2+2}{x^3+2x}\)'),
         (r'\(\dfrac{d}{dx}(\ln\sqrt{x})\)', r'\(\dfrac{1}{2x}\)'),
         (r'\(\dfrac{d}{dx}(\ln(e^x))\)', r'\(1\)'),
         (r'\(\dfrac{d}{dx}(\ln(x^2-4))\)', r'\(\dfrac{2x}{x^2-4}\)'),
         (r'\(\dfrac{d}{dx}(\ln(\sin x))\)', r'\(\dfrac{\cos x}{\sin x}=\cot x\)'),
         (r'\(\dfrac{d}{dx}(\ln(x+1))\)', r'\(\dfrac{1}{x+1}\)'),
         (r'\(\dfrac{d}{dx}(\ln(4x^2))\)', r'\(\dfrac{2}{x}\)'),
         (r'\(\dfrac{d}{dx}(\ln(x^2+x))\)', r'\(\dfrac{2x+1}{x^2+x}\)'),
         (r'\(\dfrac{d}{dx}(\ln(e^{2x}))\)', r'\(2\)'),
     ]),
_set('w4a-set2', '4A Set 2', 'WEEK 4A · SET 2 OF 3', 'Student Notes Week 4A (filled-in)',
     r'Derivatives of \(\sin x\), \(\cos x\), \(\tan x\)',
     'From Week 4A: standard trig derivatives and simple combinations.',
     [
         r'\(\dfrac{d}{dx}\sin x=\cos x\), \(\dfrac{d}{dx}\cos x=-\sin x\), \(\dfrac{d}{dx}\tan x=\sec^2 x\).',
         r'Use chain rule for \(\sin(f(x))\), etc.: derivative of outside times derivative of inside.',
         r'Know \(\sec^2 x = 1+\tan^2 x\) for rewriting answers.',
     ],
     r'\(\dfrac{d}{dx}\sin(3x)=3\cos(3x)\).',
     [r'\(\sin\'=\cos\), \(\cos\'=-\sin\), \(\tan\'=\sec^2\).', 'Chain rule on inner angle.', r'\(\sec^2 x=1+\tan^2 x\).', r'Watch signs on \(\cos\).', 'Radians assumed.'],
     [r'\(\dfrac{d}{dx}\sin x=\cos x\)', r'\(\dfrac{d}{dx}\cos x=-\sin x\)', r'\(\dfrac{d}{dx}\tan x=\sec^2 x\)', r'\(\dfrac{d}{dx}\sin(ax)=a\cos(ax)\)'],
     [
         (r'\(\dfrac{d}{dx}(\sin x)\)', r'\(\cos x\)'),
         (r'\(\dfrac{d}{dx}(\cos x)\)', r'\(-\sin x\)'),
         (r'\(\dfrac{d}{dx}(\tan x)\)', r'\(\sec^2 x\)'),
         (r'\(\dfrac{d}{dx}(\sin(2x))\)', r'\(2\cos(2x)\)'),
         (r'\(\dfrac{d}{dx}(\cos(3x))\)', r'\(-3\sin(3x)\)'),
         (r'\(\dfrac{d}{dx}(\tan(x/2))\)', r'\(\dfrac{1}{2}\sec^2(x/2)\)'),
         (r'\(\dfrac{d}{dx}(x\sin x)\)', r'\(\sin x+x\cos x\)'),
         (r'\(\dfrac{d}{dx}(\sin x+\cos x)\)', r'\(\cos x-\sin x\)'),
         (r'\(\dfrac{d}{dx}(\sin^2 x)\) via chain', r'\(2\sin x\cos x=\sin(2x)\)'),
         (r'\(\dfrac{d}{dx}(\cos(x^2))\)', r'\(-2x\sin(x^2)\)'),
         (r'\(\dfrac{d}{dx}(\tan(2x))\)', r'\(2\sec^2(2x)\)'),
         (r'\(\dfrac{d}{dx}(3\cos x)\)', r'\(-3\sin x\)'),
         (r'\(\dfrac{d}{dx}(\sin x\cdot\cos x)\)', r'\(\cos^2 x-\sin^2 x=\cos(2x)\)'),
         (r'\(\dfrac{d}{dx}(\sin(\pi x))\)', r'\(\pi\cos(\pi x)\)'),
         (r'\(\dfrac{d}{dx}(\sec^2 x)\)', r'\(2\sec^2 x\tan x\)'),
     ]),
_set('w4a-set3', '4A Set 3', 'WEEK 4A · SET 3 OF 3', 'Student Notes Week 4A (filled-in)',
     'Mixed log, exponential & trig derivatives',
     r'From Week 4A: combine rules on functions involving \(e^x\), \(\ln x\), and trig.',
     [
         r'Identify which rule applies to each factor: exponential, log, trig, product, quotient, chain.',
         r'Mixed problems are common on tests — organise work clearly.',
         r'Simplify using identities (\(\sin^2+\cos^2=1\), log laws) only when it helps.',
     ],
     r'\(\dfrac{d}{dx}[x e^x]=e^x+x e^x\); \(\dfrac{d}{dx}[\ln(\cos x)]=-\tan x\).',
     ['Pick the right rule per term.', 'Chain on compositions.', 'Product/quotient when needed.', 'Check domain (log, tan).', 'Factor final answers when neat.'],
     [r"\(\dfrac{d}{dx}e^{f}=f^{\prime}e^{f}\)", r"\(\dfrac{d}{dx}\ln f=\dfrac{f^{\prime}}{f}\)", r"\(\dfrac{d}{dx}\sin f=f^{\prime}\cos f\)"],
     [
         (r'\(\dfrac{d}{dx}(x e^x)\)', r'\(e^x+x e^x\)'),
         (r'\(\dfrac{d}{dx}(\ln x\cdot x)\)', r'\(\ln x+1\)'),
         (r'\(\dfrac{d}{dx}(e^x\sin x)\)', r'\(e^x\sin x+e^x\cos x\)'),
         (r'\(\dfrac{d}{dx}(\ln(\cos x))\)', r'\(-\tan x\)'),
         (r'\(\dfrac{d}{dx}(e^{2x}\cos x)\)', r'\(2e^{2x}\cos x-e^{2x}\sin x\)'),
         (r'\(\dfrac{d}{dx}(\tan x\cdot e^x)\)', r'\(\sec^2 x\, e^x+e^x\tan x\)'),
         (r'\(\dfrac{d}{dx}(\ln(x e^x))\)', r'\(\dfrac{x+1}{x}\)'),
         (r'\(\dfrac{d}{dx}(\sin x\cdot\ln x)\)', r'\(\cos x\ln x+\dfrac{\sin x}{x}\)'),
         (r'\(\dfrac{d}{dx}(e^{\sin x})\)', r'\(\cos x\, e^{\sin x}\)'),
         (r'\(\dfrac{d}{dx}(\dfrac{\sin x}{x})\)', r'\(\dfrac{x\cos x-\sin x}{x^2}\)'),
         (r'\(\dfrac{d}{dx}(\ln(\sin x))\)', r'\(\cot x\)'),
         (r'\(\dfrac{d}{dx}(x^2 e^{-x})\)', r'\(2x e^{-x}-x^2 e^{-x}\)'),
         (r'\(\dfrac{d}{dx}(\cos x\cdot e^{2x})\)', r'\(-\sin x\, e^{2x}+2e^{2x}\cos x\)'),
         (r'\(\dfrac{d}{dx}(\ln(x^2+1)+\sin x)\)', r'\(\dfrac{2x}{x^2+1}+\cos x\)'),
         (r'\(\dfrac{d}{dx}(e^x(\sin x+\cos x))\)', r'\(2e^x\cos x\)'),
     ]),
])

INT_GROUPS = {}

INT_GROUPS['4d'] = _grp('Week 4D — Antiderivatives', [
_set('w4d-set1', '4D Set 1', 'WEEK 4D · SET 1 OF 3', 'Student Notes Week 4D (filled-in)',
     'Introduction to indefinite integrals',
     r'From Week 4D: antiderivatives, \(\int f(x)\,dx\), and the constant of integration.',
     [
         r"An <strong>indefinite integral</strong> \(\int f(x)\,dx = F(x)+C\) where \(F^{\prime}(x)=f(x)\). \(C\) is an arbitrary constant.",
         r'Integration reverses differentiation. Check by differentiating your answer.',
         r'Notation: \(\int\) is the integral sign; \(dx\) indicates the variable of integration.',
     ],
     r'\(\int 2x\,dx = x^2+C\). Check: \(\dfrac{d}{dx}(x^2+C)=2x\).',
     [r"Antiderivative \(F\) satisfies \(F^{\prime}=f\).", r"Always add \(+C\) for indefinite integrals.", r"Differentiate to verify.", r"\(\int\) and \(\dfrac{d}{dx}\) are inverses.", r"Same family of curves differ by \(C\)."],
     [r'\(\int f(x)\,dx = F(x)+C\)', r'\(\dfrac{d}{dx}[F(x)+C]=f(x)\)', r'\(\int k\,dx=kx+C\)'],
     [
         (r'\(\int 3\,dx\)', r'\(3x+C\)'),
         (r'\(\int x\,dx\)', r'\(\dfrac{x^2}{2}+C\)'),
         (r'\(\int 2x\,dx\)', r'\(x^2+C\)'),
         (r'\(\int x^2\,dx\)', r'\(\dfrac{x^3}{3}+C\)'),
         (r'\(\int 5x^4\,dx\)', r'\(x^5+C\)'),
         (r'\(\int (4x^3)\,dx\)', r'\(x^4+C\)'),
         (r'\(\int 7\,dx\)', r'\(7x+C\)'),
         (r'\(\int -2x\,dx\)', r'\(-x^2+C\)'),
         (r'\(\int \dfrac{1}{x^2}\,dx\)', r'\(-\dfrac{1}{x}+C\)'),
         (r'\(\int \sqrt{x}\,dx\)', r'\(\dfrac{2}{3}x^{3/2}+C\)'),
         (r'\(\int (x^2+1)\,dx\)', r'\(\dfrac{x^3}{3}+x+C\)'),
         (r'\(\int 0\,dx\)', r'\(C\)'),
         (r'\(\int 6x^2\,dx\)', r'\(2x^3+C\)'),
         (r'\(\int (3x^2-2)\,dx\)', r'\(x^3-2x+C\)'),
         (r'\(\int x^{-3}\,dx\)', r'\(-\dfrac{1}{2x^2}+C\)'),
     ]),
_set('w4d-set2', '4D Set 2', 'WEEK 4D · SET 2 OF 3', 'Student Notes Week 4D (filled-in)',
     'Power rule, constant multiple & sum rules for integration',
     r'From Week 4D: \(\int x^n\,dx=\dfrac{x^{n+1}}{n+1}+C\) (\(n\neq -1\)), plus constant multiple and sum.',
     [
         r'<strong>Power rule for integration</strong>: \(\int x^n\,dx=\dfrac{x^{n+1}}{n+1}+C\) for \(n\neq -1\).',
         r'<strong>Constant multiple</strong>: \(\int kf(x)\,dx=k\int f(x)\,dx\). <strong>Sum</strong>: \(\int[f+g]=\int f+\int g\).',
         r'Integrate term by term for polynomials.',
     ],
     r'\(\int(3x^2-4x+5)\,dx=x^3-2x^2+5x+C\).',
     [r'\(\int x^n=\dfrac{x^{n+1}}{n+1}+C\), \(n\neq -1\)', 'Pull constants out.', 'Integrate sums term by term.', r'Special case \(\int x^{-1}\) is \(\ln|x|\) (later).', 'Add one to power, divide.'],
     [r'\(\int x^n\,dx=\dfrac{x^{n+1}}{n+1}+C\)', r'\(\int kf=k\int f\)', r'\(\int(f+g)=\int f+\int g\)'],
     [
         (r'\(\int 4x^3\,dx\)', r'\(x^4+C\)'),
         (r'\(\int (2x+3)\,dx\)', r'\(x^2+3x+C\)'),
         (r'\(\int (x^2-6x+1)\,dx\)', r'\(\dfrac{x^3}{3}-3x^2+x+C\)'),
         (r'\(\int 5x^2\,dx\)', r'\(\dfrac{5x^3}{3}+C\)'),
         (r'\(\int (3-2x)\,dx\)', r'\(3x-x^2+C\)'),
         (r'\(\int x^4\,dx\)', r'\(\dfrac{x^5}{5}+C\)'),
         (r'\(\int (6x^2+4)\,dx\)', r'\(2x^3+4x+C\)'),
         (r'\(\int \dfrac{x^3}{2}\,dx\)', r'\(\dfrac{x^4}{8}+C\)'),
         (r'\(\int (x^{-2})\,dx\)', r'\(-\dfrac{1}{x}+C\)'),
         (r'\(\int (4\sqrt{x})\,dx\)', r'\(\dfrac{8}{3}x^{3/2}+C\)'),
         (r'\(\int (x^2+x^{-1})\,dx\)', r'\(\dfrac{x^3}{3}+\ln|x|+C\)'),
         (r'\(\int (7x^6-1)\,dx\)', r'\(x^7-x+C\)'),
         (r'\(\int (2x^3-3x)\,dx\)', r'\(\dfrac{x^4}{2}-\dfrac{3x^2}{2}+C\)'),
         (r'\(\int \dfrac{3}{x^4}\,dx\)', r'\(-\dfrac{1}{x^3}+C\)'),
         (r'\(\int (5x^2+2x+1)\,dx\)', r'\(\dfrac{5x^3}{3}+x^2+x+C\)'),
     ]),
_set('w4d-set3', '4D Set 3', 'WEEK 4D · SET 3 OF 3', 'Student Notes Week 4D (filled-in)',
     'Simplifying the integrand before integrating',
     'From Week 4D: expand, factor, or rewrite powers before integrating.',
     [
         r'Simplify the integrand algebraically before integrating — it saves work and reduces errors.',
         r'Expand products like \((x+1)^2\), combine fractions, rewrite roots as powers.',
         r'After simplifying, use power rule and sum rule on each term.',
     ],
     r'\(\int(x+1)^2\,dx=\int(x^2+2x+1)\,dx=\dfrac{x^3}{3}+x^2+x+C\).',
     ['Expand before integrating when helpful.', r'Rewrite \(\sqrt{x}=x^{1/2}\).', 'Combine like terms.', r'Check domain for \(\ln\) terms.', 'Differentiate answer to verify.'],
     [r'\((x+a)^2=x^2+2ax+a^2\)', r'\(\sqrt[n]{x}=x^{1/n}\)', r'Simplify, then power rule'],
     [
         (r'\(\int (x+2)^2\,dx\)', r'\(\dfrac{x^3}{3}+2x^2+4x+C\)'),
         (r'\(\int (2x-1)^2\,dx\)', r'\(\dfrac{8x^3}{3}-4x^2+x+C\)'),
         (r'\(\int x(x+3)\,dx\)', r'\(\dfrac{x^3}{3}+\dfrac{3x^2}{2}+C\)'),
         (r'\(\int (x^2-1)\,dx\)', r'\(\dfrac{x^3}{3}-x+C\)'),
         (r'\(\int \dfrac{x^2+2x}{x}\,dx\)', r'\(\dfrac{x^2}{2}+2x+C\)'),
         (r'\(\int (3x+1)(x-1)\,dx\)', r'\(\dfrac{3x^3}{3}-\dfrac{3x^2}{2}-x+C=x^3-\dfrac{3x^2}{2}-x+C\)'),
         (r'\(\int \dfrac{(x+1)^2}{x^2}\,dx\)', r'\(\int(1+\dfrac{2}{x}+\dfrac{1}{x^2})\,dx=x+2\ln|x|-\dfrac{1}{x}+C\)'),
         (r'\(\int \sqrt{x}(x+1)\,dx\)', r'\(\dfrac{2x^{5/2}}{5}+\dfrac{2x^{3/2}}{3}+C\)'),
         (r'\(\int (x^3-x)/x\,dx\)', r'\(\dfrac{x^3}{3}-x+C\)'),
         (r'\(\int (4x^2+4x+1)\,dx\)', r'\(\dfrac{4x^3}{3}+2x^2+x+C\)'),
         (r'\(\int \dfrac{x^2-4}{x-2}\,dx\) for \(x\neq 2\)', r'\(\int(x+2)\,dx=\dfrac{x^2}{2}+2x+C\)'),
         (r'\(\int x^2(x-1)\,dx\)', r'\(\dfrac{x^4}{4}-\dfrac{x^3}{3}+C\)'),
         (r'\(\int (1/x+1)\,dx\)', r'\(\ln|x|+x+C\)'),
         (r'\(\int (3\sqrt{x}-2)\,dx\)', r'\(2x^{3/2}-2x+C\)'),
         (r'\(\int \dfrac{x^3+1}{x+1}\,dx\) for \(x\neq -1\)', r'\(\int(x^2-x+1)\,dx=\dfrac{x^3}{3}-\dfrac{x^2}{2}+x+C\)'),
     ]),
])

INT_GROUPS['5a'] = _grp('Week 5A — Definite integrals & area', [
_set('w5a-set1', '5A Set 1', 'WEEK 5A · SET 1 OF 3', 'Student Notes Week 5A (filled-in)',
     'Fundamental Theorem of Calculus & definite integrals',
     r"From Week 5A: evaluate \(\int_a^b f(x)\,dx = F(b)-F(a)\) where \(F^{\prime}=f\).",
     [
         r"The <strong>Fundamental Theorem of Calculus (FTC)</strong>: if \(F^{\prime}=f\), then \(\displaystyle\int_a^b f(x)\,dx = F(b)-F(a)\).",
         r'Notation: \(\displaystyle\int_a^b f(x)\,dx = \big[F(x)\big]_a^b = F(b)-F(a)\).',
         r'No \(+C\) needed for definite integrals — constants cancel.',
     ],
     r'\(\displaystyle\int_0^2 3x\,dx = \big[\tfrac{3x^2}{2}\big]_0^2 = 6\).',
     [r'Find antiderivative \(F\).', r'Evaluate \(F(b)-F(a)\).', r'No constant \(C\) in definite integrals.', 'FTC links integration and differentiation.', 'Units: area, displacement, etc.'],
     [r"\(\displaystyle\int_a^b f(x)\,dx = F(b)-F(a)\)", r"\(F^{\prime}=f\)", r"\(\displaystyle\int_a^b k\,dx = k(b-a)\)"],
     [
         (r'\(\displaystyle\int_0^1 2x\,dx\)', r'\(1\)'),
         (r'\(\displaystyle\int_0^2 x^2\,dx\)', r'\(\dfrac{8}{3}\)'),
         (r'\(\displaystyle\int_1^3 3\,dx\)', r'\(6\)'),
         (r'\(\displaystyle\int_0^1 (x+1)\,dx\)', r'\(\dfrac{3}{2}\)'),
         (r'\(\displaystyle\int_{-1}^1 x\,dx\)', r'\(0\)'),
         (r'\(\displaystyle\int_0^3 4x\,dx\)', r'\(18\)'),
         (r'\(\displaystyle\int_1^2 \dfrac{1}{x^2}\,dx\)', r'\(\dfrac{1}{2}\)'),
         (r'\(\displaystyle\int_0^2 (x^2+1)\,dx\)', r'\(\dfrac{14}{3}\)'),
         (r'\(\displaystyle\int_0^1 5x^4\,dx\)', r'\(1\)'),
         (r'\(\displaystyle\int_2^4 x\,dx\)', r'\(6\)'),
         (r'\(\displaystyle\int_0^1 \sqrt{x}\,dx\)', r'\(\dfrac{2}{3}\)'),
         (r'\(\displaystyle\int_{-2}^0 (3x^2)\,dx\)', r'\(8\)'),
         (r'\(\displaystyle\int_1^4 \dfrac{1}{x}\,dx\)', r'\(\ln 4\)'),
         (r'\(\displaystyle\int_0^{\pi/2} \cos x\,dx\)', r'\(1\)'),
         (r'\(\displaystyle\int_0^1 (2x^3-x)\,dx\)', r'\(\dfrac{1}{2}\)'),
     ]),
_set('w5a-set2', '5A Set 2', 'WEEK 5A · SET 2 OF 3', 'Student Notes Week 5A (filled-in)',
     'Definite integrals of powers & polynomials',
     'From Week 5A: practice evaluating definite integrals of polynomial and power functions.',
     [
         r'Integrate using power rule, then substitute limits.',
         r'Watch negative limits: \(\displaystyle\int_a^b = -\displaystyle\int_b^a\).',
         r'Simplify fractions in the final answer.',
     ],
     r'\(\displaystyle\int_0^2 (x^2-2x)\,dx = \big[\tfrac{x^3}{3}-x^2\big]_0^2 = \dfrac{8}{3}-4 = -\dfrac{4}{3}\).',
     ['Antiderivative then subtract.', 'Negative area possible algebraically.', 'Simplify exact fractions.', 'Check sign of integrand.', 'Limits order matters.'],
     [r'\(\displaystyle\int_a^b x^n\,dx = \dfrac{b^{n+1}-a^{n+1}}{n+1}\)', r'\(\displaystyle\int_a^b (f+g)=\int_a^b f+\int_a^b g\)'],
     [
         (r'\(\displaystyle\int_0^3 x^2\,dx\)', r'\(9\)'),
         (r'\(\displaystyle\int_1^2 (2x+1)\,dx\)', r'\(4\)'),
         (r'\(\displaystyle\int_0^1 (1-x^2)\,dx\)', r'\(\dfrac{2}{3}\)'),
         (r'\(\displaystyle\int_{-1}^0 x^3\,dx\)', r'\(-\dfrac{1}{4}\)'),
         (r'\(\displaystyle\int_0^2 (3x^2-2)\,dx\)', r'\(4\)'),
         (r'\(\displaystyle\int_1^3 (x^2-4x+3)\,dx\)', r'\(\dfrac{4}{3}\)'),
         (r'\(\displaystyle\int_0^4 \sqrt{x}\,dx\)', r'\(\dfrac{16}{3}\)'),
         (r'\(\displaystyle\int_2^5 \dfrac{1}{x^2}\,dx\)', r'\(\dfrac{3}{10}\)'),
         (r'\(\displaystyle\int_0^1 (4x^3-3x^2)\,dx\)', r'\(0\)'),
         (r'\(\displaystyle\int_{-2}^2 x^2\,dx\)', r'\(\dfrac{16}{3}\)'),
         (r'\(\displaystyle\int_0^2 (x-1)^2\,dx\)', r'\(\dfrac{1}{3}\)'),
         (r'\(\displaystyle\int_1^4 \dfrac{2}{x}\,dx\)', r'\(2\ln 4=4\ln 2\)'),
         (r'\(\displaystyle\int_0^{\pi} \sin x\,dx\)', r'\(2\)'),
         (r'\(\displaystyle\int_0^1 (x^3+x)\,dx\)', r'\(\dfrac{3}{4}\)'),
         (r'\(\displaystyle\int_{-1}^1 (x^2-1)\,dx\)', r'\(-\dfrac{4}{3}\)'),
     ]),
_set('w5a-set3', '5A Set 3', 'WEEK 5A · SET 3 OF 3', 'Student Notes Week 5A (filled-in)',
     'Area under a curve (above the axis)',
     r'From Week 5A: area between \(y=f(x)\) and the \(x\)-axis when \(f(x)\ge 0\) on \([a,b]\).',
     [
         r'If \(f(x)\ge 0\) on \([a,b]\), area \(=\displaystyle\int_a^b f(x)\,dx\).',
         r'Sketch the region. Identify limits from the problem (intercepts, given bounds).',
         r'Units\(^2\) for area; label axes in applications.',
     ],
     r'Area under \(y=x^2\) from \(0\) to \(2\) is \(\displaystyle\int_0^2 x^2\,dx=\dfrac{8}{3}\).',
     [r'Area \(=\displaystyle\int_a^b f(x)\,dx\) when \(f\ge 0\).', 'Sketch region first.', 'Find bounds from intercepts.', 'Answer in square units.', 'FTC for evaluation.'],
     [r'Area \(=\displaystyle\int_a^b y\,dx\) (above axis)', r'\(F(b)-F(a)\) for antiderivative \(F\)'],
     [
         (r'Area under \(y=x\) from \(0\) to \(3\).', r'\(\dfrac{9}{2}\)'),
         (r'Area under \(y=4\) from \(1\) to \(5\).', r'\(16\)'),
         (r'Area under \(y=x^2\) from \(0\) to \(1\).', r'\(\dfrac{1}{3}\)'),
         (r'Area under \(y=2x+1\) from \(0\) to \(2\).', r'\(6\)'),
         (r'Area under \(y=\sqrt{x}\) from \(0\) to \(4\).', r'\(\dfrac{16}{3}\)'),
         (r'Area under \(y=3-x^2\) above axis from \(-1\) to \(1\).', r'\(4\)'),
         (r'Area under \(y=\sin x\) from \(0\) to \(\pi\).', r'\(2\)'),
         (r'Area under \(y=x^2+1\) from \(0\) to \(2\).', r'\(\dfrac{14}{3}\)'),
         (r'Area under \(y=6x-x^2\) from \(0\) to \(6\).', r'\(36\)'),
         (r'Area under \(y=\dfrac{1}{x}\) from \(1\) to \(e\).', r'\(1\)'),
         (r'Area under \(y=|x|\) from \(-2\) to \(2\).', r'\(4\)'),
         (r'Area under \(y=5\) from \(0\) to \(7\).', r'\(35\)'),
         (r'Area under \(y=x^3\) from \(0\) to \(2\).', r'\(4\)'),
         (r'Area under \(y=\cos x\) from \(0\) to \(\pi/2\).', r'\(1\)'),
         (r'Area under \(y=4-x^2\) from \(-2\) to \(2\).', r'\(\dfrac{32}{3}\)'),
     ]),
])

INT_GROUPS['5b'] = _grp('Week 5B — Areas below axis & between curves', [
_set('w5b-set1', '5B Set 1', 'WEEK 5B · SET 1 OF 3', 'Student Notes Week 5B (filled-in)',
     r'Area below the \(x\)-axis',
     r'From Week 5B: when \(f(x)<0\), contribution to area uses absolute value — flip sign of integral.',
     [
         r'Area is always positive. If \(f(x)<0\) on \([a,b]\), area \(=\displaystyle\left|\int_a^b f(x)\,dx\right|=-\int_a^b f(x)\,dx\).',
         r'Equivalently: \(\displaystyle\int_a^b |f(x)|\,dx\) gives total area.',
         r'Sketch to see which parts are below the axis.',
     ],
     r'Area under \(y=-x\) from \(0\) to \(2\): \(\displaystyle\int_0^2(-x)\,dx=-2\); area \(=2\).',
     ['Area is positive.', 'Below axis: negate the integral value.', r'Sketch sign of \(f\).', r'Use \(|f|\) for total area.', 'Split at zeros if needed.'],
     [r'Area \(=\displaystyle\int_a^b |f(x)|\,dx\)', r'If \(f<0\): area \(=-\displaystyle\int_a^b f\,dx\)'],
     [
         (r'Area under \(y=-x\) from \(0\) to \(3\).', r'\(\dfrac{9}{2}\)'),
         (r'Area under \(y=x-2\) from \(0\) to \(2\).', r'\(2\)'),
         (r'Area under \(y=-x^2\) from \(-1\) to \(1\).', r'\(\dfrac{2}{3}\)'),
         (r'\(\displaystyle\int_0^2 (-3)\,dx\) (area interpretation).', r'\(6\)'),
         (r'Area under \(y=\sin x\) from \(\pi\) to \(2\pi\).', r'\(2\)'),
         (r'Area under \(y=1-x\) from \(1\) to \(3\).', r'\(2\)'),
         (r'Area under \(y=-2x\) from \(0\) to \(4\).', r'\(16\)'),
         (r'Area under \(y=x^2-4\) from \(0\) to \(2\).', r'\(\dfrac{16}{3}\)'),
         (r'\(\displaystyle\int_1^3 (2-x)\,dx\) as area.', r'\(2\)'),
         (r'Area under \(y=-\cos x\) from \(0\) to \(\pi\).', r'\(2\)'),
         (r'Area under \(y=x-4\) from \(2\) to \(6\).', r'\(8\)'),
         (r'Area under \(y=-x^2+1\) from \(1\) to \(2\).', r'\(\dfrac{2}{3}\)'),
         (r'Area under \(y=-4\) from \(0\) to \(5\).', r'\(20\)'),
         (r'Area under \(y=\sin x\) from \(-\pi\) to \(0\).', r'\(2\)'),
         (r'Area under \(y=2x-6\) from \(1\) to \(4\).', r'\(\dfrac{9}{2}\)'),
     ]),
_set('w5b-set2', '5B Set 2', 'WEEK 5B · SET 2 OF 3', 'Student Notes Week 5B (filled-in)',
     'Subdividing regions at zeros',
     r'From Week 5B: split \([a,b]\) where \(f\) changes sign; integrate each piece with correct sign.',
     [
         r'If \(f\) crosses the axis inside \([a,b]\), find zeros and split the integral at those points.',
         r'On each subinterval where \(f\ge 0\), add \(\displaystyle\int f\); where \(f\le 0\), add \(-\displaystyle\int f\).',
         r'Total area = sum of absolute contributions on each subinterval.',
     ],
     r'Area under \(y=x\) from \(-2\) to \(2\): \(\displaystyle\int_{-2}^0(-x)\,dx+\int_0^2 x\,dx=2+2=4\).',
     [r'Find zeros of \(f\) in interval.', 'Split integral at zeros.', 'Take absolute value per piece.', 'Sum areas.', 'Sketch essential.'],
     [r'Area \(=\sum \displaystyle\left|\int_{x_i}^{x_{i+1}} f\right|\)', r'Zeros solve \(f(x)=0\)'],
     [
         (r'Area under \(y=x\) from \(-1\) to \(2\).', r'\(\dfrac{5}{2}\)'),
         (r'Area under \(y=x^2-1\) from \(-2\) to \(2\).', r'\(\dfrac{8}{3}\)'),
         (r'Area under \(y=\sin x\) from \(0\) to \(2\pi\).', r'\(4\)'),
         (r'Area under \(y=x^2-4\) from \(-3\) to \(3\).', r'\(\dfrac{32}{3}\)'),
         (r'Area under \(y=x(x-2)\) from \(0\) to \(3\).', r'\(\dfrac{10}{3}\)'),
         (r'Area under \(y=x^3\) from \(-1\) to \(1\).', r'\(\dfrac{1}{2}\)'),
         (r'Area under \(y=\cos x\) from \(0\) to \(\pi\).', r'\(2\)'),
         (r'Area under \(y=x^2-x\) from \(0\) to \(2\).', r'\(\dfrac{2}{3}\)'),
         (r'Area under \(y=4-x^2\) from \(-3\) to \(3\).', r'\(\dfrac{32}{3}\)'),
         (r'Area under \(y=x^2-2x\) from \(0\) to \(3\).', r'\(\dfrac{10}{3}\)'),
         (r'Area under \(y=\sin(2x)\) from \(0\) to \(\pi\).', r'\(2\)'),
         (r'Area under \(y=x^2-9\) from \(0\) to \(5\).', r'\(\dfrac{98}{3}\)'),
         (r'Area under \(y=x|x|\) from \(-2\) to \(2\).', r'\(8\)'),
         (r'Area under \(y=x^2-x-2\) from \(-1\) to \(3\).', r'\(\dfrac{32}{3}\)'),
         (r'Area under \(y=\cos x\) from \(-\pi/2\) to \(\pi/2\).', r'\(2\)'),
     ]),
_set('w5b-set3', '5B Set 3', 'WEEK 5B · SET 3 OF 3', 'Student Notes Week 5B (filled-in)',
     'Area between two curves',
     r'From Week 5B: area between \(y=f(x)\) and \(y=g(x)\) is \(\displaystyle\int_a^b |f(x)-g(x)|\,dx\).',
     [
         r'If \(f(x)\ge g(x)\) on \([a,b]\), area \(=\displaystyle\int_a^b [f(x)-g(x)]\,dx\) (top minus bottom).',
         r'Find intersection points to set limits; sketch to see which curve is on top.',
         r'Horizontal strips: \(\displaystyle\int [x_{\text{right}}-x_{\text{left}}]\,dy\) when integrating in \(y\).',
     ],
     r'Area between \(y=x^2\) and \(y=x\) on \([0,1]\): \(\displaystyle\int_0^1(x-x^2)\,dx=\dfrac{1}{6}\).',
     ['Top curve minus bottom curve.', 'Limits from intersections.', 'Sketch both curves.', 'Integrate difference.', 'Check which is larger on interval.'],
     [r'Area \(=\displaystyle\int_a^b [f_{\text{top}}-f_{\text{bottom}}]\,dx\)', r'Intersections: solve \(f(x)=g(x)\)'],
     [
         (r'Area between \(y=x\) and \(y=x^2\) from \(0\) to \(1\).', r'\(\dfrac{1}{6}\)'),
         (r'Area between \(y=2\) and \(y=x^2\) from \(-2\) to \(2\).', r'\(\dfrac{32}{3}\)'),
         (r'Area between \(y=x\) and \(y=2-x\) from \(0\) to \(1\).', r'\(1\)'),
         (r'Area between \(y=\sin x\) and \(y=\cos x\) from \(0\) to \(\pi/4\).', r'\(\sqrt{2}-1\)'),
         (r'Area between \(y=x^2\) and \(y=2x\) from \(0\) to \(2\).', r'\(\dfrac{4}{3}\)'),
         (r'Area between \(y=4\) and \(y=x^2\) from \(0\) to \(2\).', r'\(\dfrac{16}{3}\)'),
         (r'Area between \(y=x+1\) and \(y=x^2\) from \(-1\) to \(2\).', r'\(\dfrac{9}{2}\)'),
         (r'Area between \(y=\sqrt{x}\) and \(y=x\) from \(0\) to \(1\).', r'\(\dfrac{1}{6}\)'),
         (r'Area between \(y=1\) and \(y=x^2\) from \(-1\) to \(1\).', r'\(\dfrac{4}{3}\)'),
         (r'Area between \(y=x\) and \(y=-x\) from \(-1\) to \(1\).', r'\(1\)'),
         (r'Area between \(y=e^x\) and \(y=1\) from \(0\) to \(1\).', r'\(e-2\)'),
         (r'Area between \(y=\cos x\) and \(y=\sin x\) from \(0\) to \(\pi/4\).', r'\(1-\dfrac{1}{\sqrt{2}}\)'),
         (r'Area between \(y=x^2\) and \(y=4-x^2\).', r'\(\dfrac{16\sqrt{2}}{3}\)'),
         (r'Area between \(y=x^3\) and \(y=x\) from \(0\) to \(1\).', r'\(\dfrac{1}{4}\)'),
         (r'Area between \(y=2x\) and \(y=x^2+1\) from \(0\) to \(1\).', r'\(\dfrac{1}{3}\)'),
     ]),
])

INT_GROUPS['5c'] = _grp('Week 5C — Log & trig integrals', [
_set('w5c-set1', '5C Set 1', 'WEEK 5C · SET 1 OF 3', 'Student Notes Week 5C (filled-in)',
     r'Integrating \(\dfrac{1}{x}\)',
     r'From Week 5C: \(\int \dfrac{1}{x}\,dx = \ln|x|+C\).',
     [
         r'The special case \(n=-1\) in the power rule gives \(\displaystyle\int \dfrac{1}{x}\,dx=\ln|x|+C\).',
         r"For \(\displaystyle\int \dfrac{f^{\prime}(x)}{f(x)}\,dx=\ln|f(x)|+C\) (reverse of log derivative).",
         r'Domain: \(x\neq 0\) for \(\ln|x|\).',
     ],
     r'\(\displaystyle\int \dfrac{2}{x}\,dx=2\ln|x|+C\).',
     [r'\(\int \dfrac{1}{x}=\ln|x|+C\)', r"\(\int \dfrac{f^{\prime}}{f}=\ln|f|+C\)", r'Use absolute value in \(\ln\).', 'Check by differentiating.', 'Linear numerator over function.'],
     [r'\(\displaystyle\int \dfrac{1}{x}\,dx=\ln|x|+C\)', r"\(\displaystyle\int \dfrac{f^{\prime}}{f}=\ln|f(x)|+C\)", r'\(\displaystyle\int \dfrac{k}{x}\,dx=k\ln|x|+C\)'],
     [
         (r'\(\displaystyle\int \dfrac{1}{x}\,dx\)', r'\(\ln|x|+C\)'),
         (r'\(\displaystyle\int \dfrac{3}{x}\,dx\)', r'\(3\ln|x|+C\)'),
         (r'\(\displaystyle\int \dfrac{2x}{x^2+1}\,dx\)', r'\(\ln(x^2+1)+C\)'),
         (r'\(\displaystyle\int \dfrac{1}{2x}\,dx\)', r'\(\dfrac{1}{2}\ln|x|+C\)'),
         (r'\(\displaystyle\int \dfrac{1}{x+3}\,dx\)', r'\(\ln|x+3|+C\)'),
         (r'\(\displaystyle\int \dfrac{4}{2x-1}\,dx\)', r'\(2\ln|2x-1|+C\)'),
         (r'\(\displaystyle\int \dfrac{3x^2}{x^3+1}\,dx\)', r'\(\ln|x^3+1|+C\)'),
         (r'\(\displaystyle\int \dfrac{\cos x}{\sin x}\,dx\)', r'\(\ln|\sin x|+C\)'),
         (r'\(\displaystyle\int \dfrac{-1}{x}\,dx\)', r'\(-\ln|x|+C\)'),
         (r'\(\displaystyle\int \dfrac{2}{3x}\,dx\)', r'\(\dfrac{2}{3}\ln|x|+C\)'),
         (r'\(\displaystyle\int \dfrac{1}{x-5}\,dx\)', r'\(\ln|x-5|+C\)'),
         (r'\(\displaystyle\int \dfrac{5x}{x^2+4}\,dx\)', r'\(\dfrac{5}{2}\ln(x^2+4)+C\)'),
         (r'\(\displaystyle\int_1^e \dfrac{1}{x}\,dx\)', r'\(1\)'),
         (r'\(\displaystyle\int \dfrac{e^x}{e^x+1}\,dx\)', r'\(\ln(e^x+1)+C\)'),
         (r'\(\displaystyle\int \dfrac{1}{4x}\,dx\)', r'\(\dfrac{1}{4}\ln|x|+C\)'),
     ]),
_set('w5c-set2', '5C Set 2', 'WEEK 5C · SET 2 OF 3', 'Student Notes Week 5C (filled-in)',
     r'Integrating \(\sin x\) and \(\cos x\)',
     r'From Week 5C: \(\int \sin x\,dx=-\cos x+C\), \(\int \cos x\,dx=\sin x+C\).',
     [
         r'\(\displaystyle\int \sin x\,dx=-\cos x+C\) because \(\dfrac{d}{dx}(-\cos x)=\sin x\).',
         r'\(\displaystyle\int \cos x\,dx=\sin x+C\).',
         r'For \(\displaystyle\int \sin(ax)\,dx=-\dfrac{1}{a}\cos(ax)+C\) (chain rule in reverse).',
     ],
     r'\(\displaystyle\int \cos(2x)\,dx=\dfrac{1}{2}\sin(2x)+C\).',
     [r'\(\int\sin=-\cos\)', r'\(\int\cos=\sin\)', r'Adjust for inner constant \(a\).', 'Check by differentiating.', 'Radians.'],
     [r'\(\displaystyle\int \sin x\,dx=-\cos x+C\)', r'\(\displaystyle\int \cos x\,dx=\sin x+C\)', r'\(\displaystyle\int \sin(ax)\,dx=-\dfrac{1}{a}\cos(ax)+C\)'],
     [
         (r'\(\displaystyle\int \sin x\,dx\)', r'\(-\cos x+C\)'),
         (r'\(\displaystyle\int \cos x\,dx\)', r'\(\sin x+C\)'),
         (r'\(\displaystyle\int 3\sin x\,dx\)', r'\(-3\cos x+C\)'),
         (r'\(\displaystyle\int \sin(2x)\,dx\)', r'\(-\dfrac{1}{2}\cos(2x)+C\)'),
         (r'\(\displaystyle\int \cos(3x)\,dx\)', r'\(\dfrac{1}{3}\sin(3x)+C\)'),
         (r'\(\displaystyle\int (\sin x+\cos x)\,dx\)', r'\(-\cos x+\sin x+C\)'),
         (r'\(\displaystyle\int_0^{\pi/2} \sin x\,dx\)', r'\(1\)'),
         (r'\(\displaystyle\int_0^{\pi} \cos x\,dx\)', r'\(0\)'),
         (r'\(\displaystyle\int -\cos x\,dx\)', r'\(-\sin x+C\)'),
         (r'\(\displaystyle\int 2\cos(4x)\,dx\)', r'\(\dfrac{1}{2}\sin(4x)+C\)'),
         (r'\(\displaystyle\int \sin(\pi x)\,dx\)', r'\(-\dfrac{1}{\pi}\cos(\pi x)+C\)'),
         (r'\(\displaystyle\int (\cos x-\sin x)\,dx\)', r'\(\sin x+\cos x+C\)'),
         (r'\(\displaystyle\int_0^{\pi} \sin x\,dx\)', r'\(2\)'),
         (r'\(\displaystyle\int \dfrac{\sin x}{\cos^2 x}\,dx\)', r'\(\sec x+C\)'),
         (r'\(\displaystyle\int \cos^2 x\sin x\,dx\)', r'\(-\dfrac{\cos^3 x}{3}+C\)'),
     ]),
_set('w5c-set3', '5C Set 3', 'WEEK 5C · SET 3 OF 3', 'Student Notes Week 5C (filled-in)',
     'Basic trig integrals & identities',
     r'From Week 5C: \(\int \sec^2 x\,dx=\tan x+C\), \(\int \tan x\,dx\), and simple trig combinations.',
     [
         r'\(\displaystyle\int \sec^2 x\,dx=\tan x+C\) since \(\dfrac{d}{dx}\tan x=\sec^2 x\).',
         r'\(\displaystyle\int \tan x\,dx=-\ln|\cos x|+C=\ln|\sec x|+C\).',
         r'Use identities to rewrite integrands when needed (\(\sin^2 x = \dfrac{1-\cos 2x}{2}\)).',
     ],
     r'\(\displaystyle\int \sec^2(3x)\,dx=\dfrac{1}{3}\tan(3x)+C\).',
     [r'\(\int\sec^2=\tan\)', r'\(\int\tan=-\ln|\cos|\)', 'Pythagorean identities help.', 'Watch chain rule constant.', 'Definite trig integrals common.'],
     [r'\(\displaystyle\int \sec^2 x\,dx=\tan x+C\)', r'\(\displaystyle\int \tan x\,dx=-\ln|\cos x|+C\)', r'\(\sin^2 x=\dfrac{1-\cos 2x}{2}\)'],
     [
         (r'\(\displaystyle\int \sec^2 x\,dx\)', r'\(\tan x+C\)'),
         (r'\(\displaystyle\int \tan x\,dx\)', r'\(-\ln|\cos x|+C\)'),
         (r'\(\displaystyle\int \sec^2(2x)\,dx\)', r'\(\dfrac{1}{2}\tan(2x)+C\)'),
         (r'\(\displaystyle\int \sin^2 x\,dx\)', r'\(\dfrac{x}{2}-\dfrac{\sin 2x}{4}+C\)'),
         (r'\(\displaystyle\int \cos^2 x\,dx\)', r'\(\dfrac{x}{2}+\dfrac{\sin 2x}{4}+C\)'),
         (r'\(\displaystyle\int \sin x\cos x\,dx\)', r'\(\dfrac{\sin^2 x}{2}+C\)'),
         (r'\(\displaystyle\int_0^{\pi/4} \sec^2 x\,dx\)', r'\(1\)'),
         (r'\(\displaystyle\int \dfrac{1}{\cos^2 x}\,dx\)', r'\(\tan x+C\)'),
         (r'\(\displaystyle\int \sin(2x)\,dx\)', r'\(-\dfrac{1}{2}\cos(2x)+C\)'),
         (r'\(\displaystyle\int (1+\tan^2 x)\,dx\)', r'\(\tan x+C\)'),
         (r'\(\displaystyle\int \sec x\tan x\,dx\)', r'\(\sec x+C\)'),
         (r'\(\displaystyle\int_0^{\pi/3} \cos x\,dx\)', r'\(\dfrac{\sqrt{3}}{2}\)'),
         (r'\(\displaystyle\int \dfrac{\sin x}{\cos x}\,dx\)', r'\(-\ln|\cos x|+C\)'),
         (r'\(\displaystyle\int (3\sin x+2\cos x)\,dx\)', r'\(-3\cos x+2\sin x+C\)'),
         (r'\(\displaystyle\int_0^{\pi/2} \sec^2 x\,dx\)', r'\(1\)'),
     ]),
])

INT_GROUPS['5d'] = _grp('Week 5D — Substitution', [
_set('w5d-set1', '5D Set 1', 'WEEK 5D · SET 1 OF 3', 'Student Notes Week 5D (filled-in)',
     'Simple substitution (indefinite)',
     r"From Week 5D: let \(u=g(x)\), \(du=g^{\prime}(x)\,dx\), rewrite integral in \(u\).",
     [
         r'<strong>Substitution</strong> reverses the chain rule. Choose \(u\) so that \(du\) appears (up to a constant) in the integrand.',
         r'Steps: (1) choose \(u\), (2) find \(du\), (3) substitute, (4) integrate in \(u\), (5) back-substitute.',
         r'Good choices: inside a power, inside \(\ln(\cdot)\), inside \(e^{(\cdot)}\), or denominator of a fraction.',
     ],
     r'\(\displaystyle\int 2x(x^2+1)^3\,dx\). Let \(u=x^2+1\), \(du=2x\,dx\Rightarrow \dfrac{u^4}{4}+C=\dfrac{(x^2+1)^4}{4}+C\).',
     [r'Pick \(u\) so \(du\) is in integrand.', r'Include constant factors in \(du\).', r'Integrate in \(u\).', r'Back-substitute \(u=g(x)\).', 'Check by differentiating.'],
     [r"\(u=g(x)\), \(du=g^{\prime}(x)\,dx\)", r"\(\displaystyle\int f(g(x))g^{\prime}(x)\,dx=\int f(u)\,du\)"],
     [
         (r'\(\displaystyle\int 2x(x^2+3)^4\,dx\)', r'\(\dfrac{(x^2+3)^5}{5}+C\)'),
         (r'\(\displaystyle\int x\sqrt{x^2+1}\,dx\)', r'\(\dfrac{(x^2+1)^{3/2}}{3}+C\)'),
         (r'\(\displaystyle\int \dfrac{2x}{x^2+1}\,dx\)', r'\(\ln(x^2+1)+C\)'),
         (r'\(\displaystyle\int e^{3x}\,dx\)', r'\(\dfrac{e^{3x}}{3}+C\)'),
         (r'\(\displaystyle\int \cos(2x)\,dx\)', r'\(\dfrac{1}{2}\sin(2x)+C\)'),
         (r'\(\displaystyle\int x(x^2-4)^3\,dx\)', r'\(\dfrac{(x^2-4)^4}{8}+C\)'),
         (r'\(\displaystyle\int \dfrac{1}{2x+1}\,dx\)', r'\(\dfrac{1}{2}\ln|2x+1|+C\)'),
         (r'\(\displaystyle\int x e^{x^2}\,dx\)', r'\(\dfrac{e^{x^2}}{2}+C\)'),
         (r'\(\displaystyle\int \sin x\cos x\,dx\)', r'\(\dfrac{\sin^2 x}{2}+C\)'),
         (r'\(\displaystyle\int \dfrac{x}{\sqrt{x^2+9}}\,dx\)', r'\(\sqrt{x^2+9}+C\)'),
         (r'\(\displaystyle\int (3x+1)^5\,dx\)', r'\(\dfrac{(3x+1)^6}{18}+C\)'),
         (r'\(\displaystyle\int \sec^2 x\tan x\,dx\)', r'\(\dfrac{\tan^2 x}{2}+C\)'),
         (r'\(\displaystyle\int \dfrac{e^x}{e^x+1}\,dx\)', r'\(\ln(e^x+1)+C\)'),
         (r'\(\displaystyle\int \dfrac{1}{\sqrt{1-x}}\,dx\)', r'\(-2\sqrt{1-x}+C\)'),
         (r'\(\displaystyle\int x^3(x^4+2)^2\,dx\)', r'\(\dfrac{(x^4+2)^3}{12}+C\)'),
     ]),
_set('w5d-set2', '5D Set 2', 'WEEK 5D · SET 2 OF 3', 'Student Notes Week 5D (filled-in)',
     'Definite integrals with substitution (change limits)',
     r'From Week 5D: when using substitution on \(\int_a^b\), change limits to \(u(a)\) and \(u(b)\).',
     [
         r'For definite integrals, either (1) back-substitute and use original limits, or (2) <strong>change limits</strong> to \(u\)-values.',
         r"Changing limits avoids back-substitution: \(\displaystyle\int_a^b f(g(x))g^{\prime}(x)\,dx=\int_{u(a)}^{u(b)} f(u)\,du\).",
         r'Ensure new limits correspond to \(x=a\) and \(x=b\) under your substitution.',
     ],
     r'\(\displaystyle\int_0^1 2x(x^2+1)^3\,dx\). \(u=x^2+1\): \(u(0)=1\), \(u(1)=2\Rightarrow \int_1^2 u^3\,du=\dfrac{15}{4}\).',
     [r'Change \(x\)-limits to \(u\)-limits.', 'Or back-substitute then evaluate.', r'Do not mix \(x\) and \(u\) in final step.', r'Check \(u(a)\), \(u(b)\).', r'FTC on \(u\)-integral.'],
     [r"\(\displaystyle\int_a^b f(g(x))g^{\prime}(x)\,dx=\int_{g(a)}^{g(b)} f(u)\,du\)", r'\(u=g(x)\)'],
     [
         (r'\(\displaystyle\int_0^1 2x(x^2+1)^2\,dx\)', r'\(\dfrac{7}{3}\)'),
         (r'\(\displaystyle\int_0^{\pi/2} \sin x\cos x\,dx\)', r'\(\dfrac{1}{2}\)'),
         (r'\(\displaystyle\int_0^1 x e^{x^2}\,dx\)', r'\(\dfrac{e-1}{2}\)'),
         (r'\(\displaystyle\int_1^2 \dfrac{2x}{x^2+1}\,dx\)', r'\(\ln\dfrac{5}{2}\)'),
         (r'\(\displaystyle\int_0^{\pi/4} \sec^2 x\,dx\)', r'\(1\)'),
         (r'\(\displaystyle\int_0^2 x\sqrt{x^2+4}\,dx\)', r'\(\dfrac{8\sqrt{2}-8}{3}\)'),
         (r'\(\displaystyle\int_0^1 \dfrac{x}{\sqrt{x^2+1}}\,dx\)', r'\(\sqrt{2}-1\)'),
         (r'\(\displaystyle\int_0^{\ln 2} e^{2x}\,dx\)', r'\(\dfrac{3}{2}\)'),
         (r'\(\displaystyle\int_0^{\pi/3} \sin(3x)\,dx\)', r'\(\dfrac{2}{3}\)'),
         (r'\(\displaystyle\int_1^e \dfrac{1}{x\ln x}\,dx\)', r'\(0\)'),
         (r'\(\displaystyle\int_0^1 (3x+1)^4\,dx\)', r'\(\dfrac{1023}{15}\)'),
         (r'\(\displaystyle\int_0^{\pi/6} \cos(2x)\,dx\)', r'\(\dfrac{\sqrt{3}}{4}\)'),
         (r'\(\displaystyle\int_0^2 \dfrac{x}{x^2+4}\,dx\)', r'\(\dfrac{1}{2}\ln 2\)'),
         (r'\(\displaystyle\int_0^1 x(x^2+3)^3\,dx\)', r'\(\dfrac{40}{3}\)'),
         (r'\(\displaystyle\int_0^{\pi/4} \tan x\,dx\)', r'\(\dfrac{1}{2}\ln 2\)'),
     ]),
_set('w5d-set3', '5D Set 3', 'WEEK 5D · SET 3 OF 3', 'Student Notes Week 5D (filled-in)',
     'More substitution practice',
     r'From Week 5D: harder choices of \(u\) and integrals needing algebraic adjustment.',
     [
         r'Sometimes multiply/divide by a constant to make \(du\) appear.',
         r"For \(\displaystyle\int \dfrac{f^{\prime}(x)}{\sqrt{f(x)}}\,dx\), try \(u=f(x)\).",
         r'Always differentiate your answer to verify.',
     ],
     r'\(\displaystyle\int x\sqrt{1-x^2}\,dx\). \(u=1-x^2\), \(du=-2x\,dx\Rightarrow -\dfrac{1}{2}\int\sqrt{u}\,du=-\dfrac{u^{3/2}}{3}+C\).',
     [r'Adjust constants to match \(du\).', r'Try \(u=\) inside function.', 'Definite: change limits.', 'Back-substitute for indefinite.', 'Verify by differentiation.'],
     [r'Multiply by \(k\) to get \(du\)', r"\(\displaystyle\int \dfrac{f^{\prime}}{\sqrt{f}}=2\sqrt{f}+C\)"],
     [
         (r'\(\displaystyle\int x\sqrt{1-x^2}\,dx\)', r'\(-\dfrac{(1-x^2)^{3/2}}{3}+C\)'),
         (r'\(\displaystyle\int \dfrac{x^2}{(x^3+1)^2}\,dx\)', r'\(-\dfrac{1}{3(x^3+1)}+C\)'),
         (r'\(\displaystyle\int \dfrac{\ln x}{x}\,dx\)', r'\(\dfrac{(\ln x)^2}{2}+C\)'),
         (r'\(\displaystyle\int \dfrac{e^{2x}}{e^{2x}+1}\,dx\)', r'\(\dfrac{1}{2}\ln(e^{2x}+1)+C\)'),
         (r'\(\displaystyle\int \sin^3 x\cos x\,dx\)', r'\(\dfrac{\sin^4 x}{4}+C\)'),
         (r'\(\displaystyle\int \dfrac{1}{x\sqrt{\ln x}}\,dx\)', r'\(2\sqrt{\ln x}+C\)'),
         (r'\(\displaystyle\int x^2 e^{x^3}\,dx\)', r'\(\dfrac{e^{x^3}}{3}+C\)'),
         (r'\(\displaystyle\int \dfrac{\cos x}{\sin^2 x}\,dx\)', r'\(-\dfrac{1}{\sin x}+C\)'),
         (r'\(\displaystyle\int \dfrac{2x+1}{(x^2+x+1)^2}\,dx\)', r'\(-\dfrac{1}{x^2+x+1}+C\)'),
         (r'\(\displaystyle\int_0^1 \dfrac{x}{\sqrt{x^2+1}}\,dx\)', r'\(\sqrt{2}-1\)'),
         (r'\(\displaystyle\int \tan x\sec^2 x\,dx\)', r'\(\dfrac{\tan^2 x}{2}+C\)'),
         (r'\(\displaystyle\int \dfrac{x}{x^2-1}\,dx\)', r'\(\dfrac{1}{2}\ln|x^2-1|+C\)'),
         (r'\(\displaystyle\int e^x\sqrt{e^x+1}\,dx\)', r'\(\dfrac{2(e^x+1)^{3/2}}{3}+C\)'),
         (r'\(\displaystyle\int \dfrac{1}{\sqrt{4-x^2}}\,dx\)', r'\(\arcsin(x/2)+C\)'),
         (r'\(\displaystyle\int_0^{\pi/2} \dfrac{\sin x}{1+\cos^2 x}\,dx\)', r'\(\dfrac{\pi}{4}\)'),
     ]),
])

INT_GROUPS['6a'] = _grp('Week 6A — Further substitution', [
_set('w6a-set1', '6A Set 1', 'WEEK 6A · SET 1 OF 3', 'Student Notes Week 6A (filled-in)',
     'Substitution with exponential composites',
     r'From Week 6A: integrals involving \(e^{f(x)}\) and related forms.',
     [
         r"For \(\displaystyle\int f^{\prime}(x)e^{f(x)}\,dx\), let \(u=f(x)\) gives \(e^u+C\).",
         r'Exponential composites often pair with the derivative of the exponent.',
         r'Adjust constants when the derivative differs by a factor.',
     ],
     r'\(\displaystyle\int 3e^{3x}\,dx=e^{3x}+C\). Or \(\displaystyle\int x e^{x^2}\,dx=\dfrac{e^{x^2}}{2}+C\).',
     [r"\(\int f^{\prime}e^f=e^f+C\)", 'Match derivative of exponent.', 'Scale constants as needed.', 'Change limits for definite.', 'Check by differentiating.'],
     [r"\(\displaystyle\int f^{\prime}(x)e^{f(x)}\,dx=e^{f(x)}+C\)", r'\(\displaystyle\int e^{ax}\,dx=\dfrac{e^{ax}}{a}+C\)'],
     [
         (r'\(\displaystyle\int e^{5x}\,dx\)', r'\(\dfrac{e^{5x}}{5}+C\)'),
         (r'\(\displaystyle\int x e^{x^2}\,dx\)', r'\(\dfrac{e^{x^2}}{2}+C\)'),
         (r'\(\displaystyle\int e^{2x+1}\,dx\)', r'\(\dfrac{e^{2x+1}}{2}+C\)'),
         (r'\(\displaystyle\int \dfrac{e^x}{e^x+1}\,dx\)', r'\(\ln(e^x+1)+C\)'),
         (r'\(\displaystyle\int x^2 e^{x^3}\,dx\)', r'\(\dfrac{e^{x^3}}{3}+C\)'),
         (r'\(\displaystyle\int e^{-x}\,dx\)', r'\(-e^{-x}+C\)'),
         (r'\(\displaystyle\int 2e^{2x}\,dx\)', r'\(e^{2x}+C\)'),
         (r'\(\displaystyle\int \dfrac{e^{2x}}{e^{2x}+3}\,dx\)', r'\(\dfrac{1}{2}\ln(e^{2x}+3)+C\)'),
         (r'\(\displaystyle\int x e^{-x^2}\,dx\)', r'\(-\dfrac{e^{-x^2}}{2}+C\)'),
         (r'\(\displaystyle\int e^x(1+e^x)\,dx\)', r'\(e^x+\dfrac{e^{2x}}{2}+C\)'),
         (r'\(\displaystyle\int_0^1 x e^{x^2}\,dx\)', r'\(\dfrac{e-1}{2}\)'),
         (r'\(\displaystyle\int e^{x/2}\,dx\)', r'\(2e^{x/2}+C\)'),
         (r'\(\displaystyle\int \dfrac{e^{\sqrt{x}}}{\sqrt{x}}\,dx\)', r'\(2e^{\sqrt{x}}+C\)'),
         (r'\(\displaystyle\int (e^x+e^{-x})\,dx\)', r'\(e^x-e^{-x}+C\)'),
         (r'\(\displaystyle\int x^3 e^{x^4}\,dx\)', r'\(\dfrac{e^{x^4}}{4}+C\)'),
     ]),
_set('w6a-set2', '6A Set 2', 'WEEK 6A · SET 2 OF 3', 'Student Notes Week 6A (filled-in)',
     'Substitution with trigonometric composites',
     r"From Week 6A: integrals like \(\int \sin^n x\cos x\,dx\), \(\int f^{\prime}(x)\sin(f(x))\,dx\), etc.",
     [
         r"For \(\displaystyle\int \sin(f(x))f^{\prime}(x)\,dx=-\cos(f(x))+C\). Similarly \(\displaystyle\int \cos(f(x))f^{\prime}(x)\,dx=\sin(f(x))+C\).",
         r'Odd powers of \(\sin\) or \(\cos\) pair well with the other trig factor\'s derivative.',
         r'Use identities to simplify when direct substitution is unclear.',
     ],
     r'\(\displaystyle\int \sin^2 x\cos x\,dx\). Let \(u=\sin x\Rightarrow \dfrac{u^3}{3}+C\).',
     [r"\(\int \sin(f)f^{\prime}=-\cos(f)+C\)", r"\(\int \cos(f)f^{\prime}=\sin(f)+C\)", r'Odd-power trig: substitute \(u=\sin\) or \(u=\cos\).', 'Pythagorean identities help.', 'Radians.'],
     [r'\(\displaystyle\int \sin^n x\cos x\,dx=\dfrac{\sin^{n+1}x}{n+1}+C\)', r'\(\displaystyle\int \cos^n x\sin x\,dx=-\dfrac{\cos^{n+1}x}{n+1}+C\)'],
     [
         (r'\(\displaystyle\int \sin^3 x\cos x\,dx\)', r'\(\dfrac{\sin^4 x}{4}+C\)'),
         (r'\(\displaystyle\int \cos^3 x\sin x\,dx\)', r'\(-\dfrac{\cos^4 x}{4}+C\)'),
         (r'\(\displaystyle\int \sin(2x)\,dx\)', r'\(-\dfrac{1}{2}\cos(2x)+C\)'),
         (r'\(\displaystyle\int \cos(5x)\,dx\)', r'\(\dfrac{1}{5}\sin(5x)+C\)'),
         (r'\(\displaystyle\int \sin x\cos^2 x\,dx\)', r'\(-\dfrac{\cos^3 x}{3}+C\)'),
         (r'\(\displaystyle\int \tan x\sec^2 x\,dx\)', r'\(\dfrac{\tan^2 x}{2}+C\)'),
         (r'\(\displaystyle\int \dfrac{\cos x}{\sin x}\,dx\)', r'\(\ln|\sin x|+C\)'),
         (r'\(\displaystyle\int \sin^2(3x)\cos(3x)\,dx\)', r'\(\dfrac{\sin^3(3x)}{9}+C\)'),
         (r'\(\displaystyle\int \sec^2 x\tan x\,dx\)', r'\(\dfrac{\tan^2 x}{2}+C\)'),
         (r'\(\displaystyle\int \cos^2 x\sin x\,dx\)', r'\(-\dfrac{\cos^3 x}{3}+C\)'),
         (r'\(\displaystyle\int_0^{\pi/2} \sin x\cos x\,dx\)', r'\(\dfrac{1}{2}\)'),
         (r'\(\displaystyle\int \sin(4x)\cos(4x)\,dx\)', r'\(\dfrac{\sin^2(4x)}{16}+C\)'),
         (r'\(\displaystyle\int \dfrac{1}{\cos^2 x}\,dx\)', r'\(\tan x+C\)'),
         (r'\(\displaystyle\int \sin x\,e^{\cos x}\,dx\)', r'\(-e^{\cos x}+C\)'),
         (r'\(\displaystyle\int \cos x\,e^{\sin x}\,dx\)', r'\(e^{\sin x}+C\)'),
     ]),
_set('w6a-set3', '6A Set 3', 'WEEK 6A · SET 3 OF 3', 'Student Notes Week 6A (filled-in)',
     'Further substitution — mixed composites',
     'From Week 6A: combine exponential, log, and trig substitutions in harder problems.',
     [
         r'Look for an inner function whose derivative (up to constant) appears in the integrand.',
         r'Mixed problems may need algebra first (expand, simplify) before substituting.',
         r'For definite integrals, change limits or back-substitute consistently.',
     ],
     r'\(\displaystyle\int \dfrac{x}{\sqrt{x^2+1}}\,dx=\sqrt{x^2+1}+C\) (let \(u=x^2+1\)).',
     ['Identify inner function.', 'Algebraic prep if needed.', 'Change limits for definite.', 'Verify answer.', 'Combine techniques from Week 5D–6A.'],
     [r"\(\displaystyle\int \dfrac{f^{\prime}}{\sqrt{f}}=2\sqrt{f}+C\)", r"\(\displaystyle\int \dfrac{f^{\prime}}{f}=\ln|f|+C\)", r"\(\displaystyle\int f^{\prime}e^f=e^f+C\)"],
     [
         (r'\(\displaystyle\int \dfrac{x}{\sqrt{x^2+4}}\,dx\)', r'\(\sqrt{x^2+4}+C\)'),
         (r'\(\displaystyle\int \dfrac{e^x-e^{-x}}{e^x+e^{-x}}\,dx\)', r'\(\ln(e^x+e^{-x})+C\)'),
         (r'\(\displaystyle\int x\sqrt{x+1}\,dx\)', r'\(\dfrac{2(x+1)^{5/2}}{5}-\dfrac{2(x+1)^{3/2}}{3}+C\)'),
         (r'\(\displaystyle\int \dfrac{\sin(\ln x)}{x}\,dx\)', r'\(-\cos(\ln x)+C\)'),
         (r'\(\displaystyle\int \dfrac{1}{x\ln x}\,dx\)', r'\(\ln|\ln x|+C\)'),
         (r'\(\displaystyle\int e^x\sin(e^x)\,dx\)', r'\(-\cos(e^x)+C\)'),
         (r'\(\displaystyle\int \dfrac{2x+3}{x^2+3x}\,dx\)', r'\(\ln|x^2+3x|+C\)'),
         (r'\(\displaystyle\int \cos x\,e^{\sin x}\,dx\)', r'\(e^{\sin x}+C\)'),
         (r'\(\displaystyle\int \dfrac{x^3}{x^4+1}\,dx\)', r'\(\dfrac{1}{4}\ln(x^4+1)+C\)'),
         (r'\(\displaystyle\int_0^1 \dfrac{2x}{x^2+1}\,dx\)', r'\(\ln 2\)'),
         (r'\(\displaystyle\int \dfrac{\sec^2 x}{\tan x}\,dx\)', r'\(\ln|\tan x|+C\)'),
         (r'\(\displaystyle\int x^2\cos(x^3)\,dx\)', r'\(\dfrac{1}{3}\sin(x^3)+C\)'),
         (r'\(\displaystyle\int \dfrac{1}{x^2\sqrt{x^2+1}}\,dx\)', r'\(-\dfrac{\sqrt{x^2+1}}{x}+C\)'),
         (r'\(\displaystyle\int \dfrac{\ln x}{x\sqrt{1+(\ln x)^2}}\,dx\)', r'\(\sqrt{1+(\ln x)^2}+C\)'),
         (r'\(\displaystyle\int_0^{\pi/4} \dfrac{\sec^2 x}{1+\tan x}\,dx\)', r'\(\ln 2\)'),
     ]),
])


def main():
    root = Path(__file__).resolve().parent / 'siddharth' / 'dpen22' / 'class-notes'
    validate(LD_GROUPS)
    validate(INT_GROUPS)
    generate(
        root / 'limits-diff' / 'lessons',
        'Limits + Differentiation',
        LD_GROUPS,
        'Limits & differentiation lesson packs (Week 2D–4A)',
        'Built from filled-in student notes: Week <strong>2D</strong> (limits), then <strong>3A–3D</strong> and <strong>4A</strong> (differentiation), 3 sets each.',
        extra_nav='<a href="../../tests/limits-diff-questions.html">Limits &amp; Diff practice tests</a>',
    )
    generate(
        root / 'integration' / 'lessons',
        'Integration',
        INT_GROUPS,
        'Integration lesson packs (Week 4D–6A)',
        'Built from filled-in student notes: Week <strong>4D</strong> (antiderivatives), <strong>5A–5D</strong> and <strong>6A</strong> (definite integrals, area, substitution), 3 sets each.',
        extra_nav='<a href="../../tests/integration-questions.html">Integration practice tests</a>',
    )


if __name__ == '__main__':
    main()
